### ISSUE TITLE
Conversion Measurement API 2021 Goals

### ISSUE THREAD

**Issue by eriktaubeneck** [WICG/attribution-reporting-api#100]
# Context
In the [January 11th] meeting, we discussed setting goals for the group for the year. As we consider any form of conversion measurement, the flow generally follows the following pattern:

1. Private data storage within the browser.
2. Computation on private data in an inaccessible scope.
3. Private reporting from the browser directly to a reporting domain.
4. Private reporting from the browser via the aggregate reporting API/MPC.

We discussed prioritizing initial use cases to be supported, and reflecting what would need to be built across each of these steps.

In addition, we agreed to set a goal for writing down the threat model under which we consider proposals and solutions.

Below, I have some proposed goals, but these are just meant to be initial suggestions to align on with the group. Once aligned, we can either update this issue, or move this into a markdown file within the repo.

# Goal Tracking
## Private data storage within the browser
Being able to store data to a write-only data storage is  implicitly included in almost every proposal in/around privacy sandbox, e.g. click and conversion reporting, adding a browser to a TURTLEDOVE interest group, etc.
### Use Cases
**Click Through Impression Declaration**
- ✅ [Adopt Proposal](https://github.com/WICG/conversion-measurement-api#impression-declaration)
- ✅ Experimental Code
- ✅ Origin Trial

**Conversion Registration**
- [Adopt Proposal](https://github.com/WICG/conversion-measurement-api#conversion-registration)
- Experimental Code
- Origin Trial

**App-to-Web Click Through / View Through Impression Declaration**
- Adopt Proposal
- Experimental Code
- Origin Trial

**View Through Impression Declaration**
- Adopt Proposal

**Generic Private Event Declaration**
- Adopt Proposal
    - Existing Proposals
        - [SPURFOWL](https://github.com/AdRoll/privacy/blob/main/SPURFOWL.md)

### Open questions:
1. Should we prioritize a generic approach which supports the above use cases, rather than these individual use cases? If so
    a. Do we need any specific structure (like proposed by SPURFOWL), or could we just use a JavaScript object which is outside the window scope, and effectively read-only from the window?
    b. Should we consider non-reporting but related ideas, like adding a [browser into an interest group in TURTLEDOVE](https://github.com/WICG/turtledove/blob/master/FLEDGE.md#11-joining-interest-groups)?

## Computation on private data in an inaccessible scope
In the current proposals, this is often rolled in with the reporting section. Within the context of ad impression conversion attribution, this is the computation required to assign attribution credit of a conversion to some set of impressions (all stored privately).
### Use Cases
**Conversion Attribution**
- Adopt Proposal

**Federated Learning**
- Adopt Proposal
    - Existing Proposals
        - [COWBIRD](https://github.com/AdRoll/privacy/blob/main/COWBIRD.md)

### Open questions:
1. Should we even consider this separately from private reporting?
2. Should we consider a general purpose JavaScript environment in an inaccessible scope which cannot affect the DOM?

### Use Cases
**Event Level Click Through Conversion Reporting**
- ✅ [Adopt Proposal](https://github.com/WICG/conversion-measurement-api#sending-scheduled-reports)
- ✅ Experimental Code
- ✅ Origin Trial

**Event Level App-to-Web Click Through Conversion Reporting**
- Adopt Proposal
- Experimental Code
- Origin Trial

**View Through Conversion Reporting**
- Adopt Proposal

**Generic Private Event Reporting**
- Adopt Proposal
    - Existing Proposals
        - [SPURFOWL reporting](https://github.com/AdRoll/privacy/blob/main/SPURFOWL.md#private-functions-for-reporting)

### Open Questions
1. If conversion attribution is broken out into the “computation on private data” step, can we reduce all conversion reporting use cases into a single use case?
2. Is there a generic reporting solution which still provides the necessary DP properties?

## Private reporting from the browser via the aggregate reporting API/MPC
Currently, the [Aggregate Reporting API](https://github.com/csharrison/aggregate-reporting-api#example-reach-measurement-for-an-ad-campaign) has been proposed, however there aren’t specific use cases attached. Primary goal is to identify the priority use cases.
### Goals
- Identify potential use cases
    - Examples
        - Reach and Frequency
        - Federated Learning
        - Verification of event-level API reports
- [Adopt Proposal for MPC Aggregation Service](https://github.com/WICG/conversion-measurement-api/blob/master/SERVICE.md)

### Goals
- Adopt Threat Model

### Open Questions
1. How should we take practicality and cost into consideration of the threat model (as opposed to worst case?)
2. Should the threat model address fraud prevention, or should that be a different model?

**Comment by michaelkleber** [comment]
Hey @eriktaubeneck I'm confused by all of the checkboxes in this issue — what are you trying to communicate with this structure?

**Comment by eriktaubeneck** [comment]
Hi @michaelkleber, checkboxes are meant to convey goals for 2021, however these are just a collection of potential goals from what I've seen across this group and proposals/ideas discussed in the web-adv group. I'm mostly trying to help provide structure to help foster communication around what should be goals, rather than suggest all of these should actually be goals (in fact, including all of these is most likely too ambitious for 2021.)

**Comment by eriktaubeneck** [comment]
TIL checkmarks in GitHub issue do not carry global state. Will update with something similar that does. Thanks for clarifying @michaelkleber

**Comment by csharrison** [comment]
Hey Erik sorry for the delay here. In general I think this structure is OK. I just made a few edits to make clear what the current Origin Trial covers. In general I am cautious about expanding the scope of this proposal to all generic measurement as opposed to conversion measurement, but I'm happy to discuss it more.

To try to answer a few of the specific open questions:
> a. Do we need any specific structure (like proposed by SPURFOWL), or could we just use a JavaScript object which is outside the window scope, and effectively read-only from the window?

I think we might want structure if we go down the path of a generic API. There are a few reasons why:
 - The browser can understand individual data pieces input into storage
 - Easier to do fine-grained privacy budgeting
 - Better controls around x-site data mixing
 - (Potentially) better transparency in the browser

> b. Should we consider non-reporting but related ideas, like adding a browser into an interest group in TURTLEDOVE?

I would prefer keeping this proposal focused on measurement, though it's possible we may land on a shared solution.

> Should we consider a general purpose JavaScript environment in an inaccessible scope which cannot affect the DOM?

I think this is a good idea, although making things declarative has a downside that many existing measurement pings are HTTP only. Will all advertiser's be OK with Javascript being run on their site by a third party?

**Comment by eriktaubeneck** [comment]
LGTM!

>  In general I am cautious about expanding the scope of this proposal to all generic measurement as opposed to conversion measurement, but I'm happy to discuss it more.

Totally reasonable. I'd suggest a couple things:
1. Update the relevant goals with a first goal of "Consider generic event [declaration|computing|reporting]"
2. Open a new issue to specifically discuss what a generic API might look like, including the items you mention above.

Apologies that I wasn't able to attend today's meeting, but it looks like the _generic vs purpose-built API_ agenda item is top of the list for the next call. I'll make sure to open a new issue on that, so we might have a bit of back and forth before that call.
