### ISSUE TITLE
Unclear fraud prevention strategy for view-through

### ISSUE THREAD

**Issue by eriktaubeneck** [WICG/attribution-reporting-api#101]
For simplicity, make the following assumptions:
1. We're using *last touch attribution* so that 100% of the attribution credit goes to the last registered click. 
2. A publisher is able to register an unlimited number of views during a session.
3. The browser is unable to verify that a view actually occurred.

Now, suppose that publisher has some set `C` of campaign ids which have been purchased across all advertisers it does business with. If the publisher is acting fraudulently, then to maximize it's chance of being the last touch, it registers views for all campaign ids in `C`.

Our current fraud prevention method had the publisher minding a token (which is blinded by the browser), so that the advertiser can verify that the report isn't forged from a different fraudulent actor. As such, if the publisher is expected to be delivering ads, the token will seem legitimate.

### Weakening assumptions
1. Even if we aren't using *last touch attribution*, nearly all attribution models take into account recency and volume of impressions across different publisher, so the incentive to fraudulently over report remains.
2. Even if we limit the number of views that can be reported, the incentive to use any excess views to fraudulently over report remains.
3. It unclear to me how the browser could verify this, but it would likely solve the issue.

### Potential Solution
If we assumpe an advertiser knows how many impressions it has purchased from a publisher (this may be an overly optimistic assumption in some settings,) then we could use the aggregate reporting API to report the total number of views issued by a publisher linking to an advertiser. At this point, an advertiser would be able to identify publishers who are over reporting (at least grossly) views.

**Comment by csharrison** [comment]
I think this is making an additional assumption, that we are doing some LDP mechanism so can't reliably authenticate to conversions? Otherwise it seems reasonable.

> As such, if the publisher is expected to be delivering ads, the token will seem legitimate.

I think the advertiser / advertiser's ad-tech can do something smarter here. When doing token issuance you can verify that the view was legitimate, etc right?

**Comment by eriktaubeneck** [comment]
I don't believe there is any need to assume there is an LDP mechanism. The only assumption I'm really making is that views will essentially work like clicks as described in the [**Multiple sources for the same trigger (Multi-touch)**](https://github.com/WICG/conversion-measurement-api#multiple-sources-for-the-same-trigger-multi-touch) section of the explainer:
> If multiple sources were clicked and associated with a single attribution trigger, send reports for all of them.
>
> To provide additional utility, the browser can choose to provide additional annotations to each of these reports, attributing credits for the triggering redirect to them individually. Attribution models allow for more sophisticated, accurate measurement.
>
> The default attribution model will be last-click attribution, giving the last-clicked source for a given trigger redirect all of the credit.
>
> To remain flexible, the browser sends an credit of value 0 to 100 for all reports associated with a single trigger. This represents the percent of attribution a source received. The sum of credits across a set of reports for one trigger should equal 100.

I am then considering a malicious source which is willing to report fraudulent views in order to maximize their likelihood of having a view in the window of time eligible for a report, and being the report with a `credit` value of 100. Once we assume they are acting fraudulently, their incentives are to report as many views as possible, to maximize their likelihood of being attributed to a trigger even in the future.

The crux of the attack is that because the views remain in the browser and reports are only issued upon a trigger event on the attributeon domain, the over reporting of views is hidden from the attributeon.

You also suggest:
> I think the advertiser / advertiser's ad-tech can do something smarter here. When doing token issuance you can verify that the view was legitimate, etc right?

For the click case, the current proposed flow (as I understand it) is:
1. User clicks from `source` to `attributeon`, and browser asks `source` for a token. Browser blinds the token and stores it. Let's call it `source_token`.
2. User performs action on `attributeon` which they wish to trigger attribution. They call the provided API, and provide a token that the browser also linds and stores. Let's call it `trigger_token`.
3. The browser performs the noise, delay, and attribution process. When it's time to send the reports, it includes both `source_token` and `trigger_token`, which act as authentication (since reports are sent to an open `.well-known` path.)

Are you suggesting adding a new step at the beginning, where at the time of an impression (or potentially sometime before) the attributeon generates a token for the source which can be passed along with the other tokens?
This would certainly help, but I'm not entire sure how it would work in the ad bidding flow. This isn't universal, but typically a DSP receives multiple bids for a potential impression. If the token is passed along at this point, a malicious source would report views for all of those bids, even though only one is displayed.

**Comment by csharrison** [comment]
> Are you suggesting adding a new step at the beginning, where at the time of an impression (or potentially sometime before) the attributeon generates a token for the source which can be passed along with the other tokens?

Yeah I'm thinking of a flow like this. In our case we were thinking of having the token be issued from the reportto / reporting origin in both the impression and conversion paths.

Then when you receive a report, you can have two tokens sent alongside it which verify. Let's discuss in the next meeting.

**Comment by csharrison** [comment]
It turns out that issuing a token on the impression side breaks differential privacy, so we could not implement that. Our proposal in this space is here:
https://github.com/WICG/attribution-reporting-api/blob/main/report_verification.md

Which just does token issuance at conversion time. Closing for now but please open a new issue if there's feedback on that proposal.
