### ISSUE TITLE
Clarify which method to use for registering trigger

### ISSUE THREAD

**Issue by alois-bissuel** [WICG/attribution-reporting-api#1028]
Hello,

On the [event-level documentation](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#triggering-attribution), there are two ways to register a trigger, either by adding an `attributionsrc` attribute on a pixel tag, or doing the request directly with `window.fetch` with two options (the booleans `eventSourceEligible` and `triggerEligible`).

There are differences between these two registration means:

First of all, the header to indicate that the request is eligible for ARA is not the same. When using the `attributionsrc` attribute, the request header is `Attribution-Reporting-Eligible: trigger, source` (which might be greased). Using the JS fetch method, the two aforementioned booleans are passed as header. From what I gather of my quick reading of the [Network monkeypatch section](https://wicg.github.io/attribution-reporting-api/#network-monkeypatches) of the definition of the API, it seems they are equivalent, though this feels unsettling if one uses the header to superficially check that the requests are valid ARA registrations. Is this the expected behavior?

The second difference lies in the debugging mode. The request generated by the `attributionsrc` parameter attaches the cookies to the header, and uses the `set-cookie` in the response to set the `ar_debug` cookie needed for debug. The JS request does not attach the cookies and does not read the `set-cookie` header of the response. This meant that the request generates **no** verbose debug report. I could make the make the JS request properly forward the cookie and set the debug cookie by adding the option `credentials: "include"` to the fetch call. Is it the correct way to do it? If so, I believe the event-level documentation should be updated to reflect this, as the two ways of registering triggers should be functionally equivalent.

Thanks a lot!

P.S. I filed this here and not in the dev-support repo as this concerns the documentation of this repo. I will be happy to refile it there if needed.

**Comment by csharrison** [comment]
Hey @alois-bissuel , two things:

1. Using the pixel tag should allow you to register sources, so there may be a bug either in your deployment or in Chromium if you're only seeing `trigger` eligibility. You can see [here](https://wicg.github.io/attribution-reporting-api/#ref-for-element-attrdef-img-attributionsrc) that we set the eligibility to both event sources and triggers. The [demo page](https://arapi-publisher.web.app/view-element-img) shows this working correctly for an image source.

1. Yes I believe this is correct. We can update the documentation to be more clear about this.

**Comment by alois-bissuel** [comment]
Thanks for the quick answer.

1. Indeed, the header is `Attribution-Reporting-Eligible: trigger, source`, so that the pixel integration can be used to register both event sources and trigger. The issue which I want to raise is the two types of headers (ie`Attribution-Reporting-Eligible` or the two `eventSourceEligible` and `triggerEligible`) which indicate that the request is eligible for ARA. This is slightly confusing.
2. Thanks for the confirmation!

**Comment by apasel422** [comment]
> The issue which I want to raise is the two types of headers (ie`Attribution-Reporting-Eligible` or the two `eventSourceEligible` and `triggerEligible`) which indicate that the request is eligible for ARA. This is slightly confusing.

Could you clarify what you mean by "two types of headers"? The `Attribution-Reporting-Eligible` request header has only one format (a structured dictionary whose keys are a subset of `{event-source, navigation-source, trigger}`) in both [the specification](https://wicg.github.io/attribution-reporting-api/#set-attribution-reporting-headers) and Chromium's implementation.

**Comment by alois-bissuel** [comment]
Sorry for the very bad wording in my question. Let me try to reformulate.
When using the `attributionsrc` attribute in an image, the request has the header `Attribution-Reporting-Elgible` (correctly filled in and possibly greased).
When using the fetch API, there is no such header present in the request, but two headers which are named `eventSourceEligible` and `triggerEligible`. Is it the same functionally?
![Fetch request headers](https://github.com/WICG/attribution-reporting-api/assets/41194547/56c28dfe-8cfa-4864-9563-834ce887447b)

**Comment by apasel422** [comment]
> When using the fetch API, there is no such header present in the request, but two headers which are named `eventSourceEligible` and `triggerEligible`.

Chromium never sets headers with those names. Is it possible that your registration code is accidentally doing:

```js
const headers = {
  eventSourceEligible: false,
  triggerEligible: true,
};
window.fetch("...", { keepalive: true, headers });
```

instead of

```js
const attributionReporting = {
  eventSourceEligible: false,
  triggerEligible: true,
};
window.fetch("...", { keepalive: true, attributionReporting });
```

?

**Comment by alois-bissuel** [comment]
Sorry for my late answer. Indeed I had messed up with the call of fetch. Closing as everything is fine now!
