### ISSUE TITLE
Support of attributionsrc by DCM and other third party ad servers

### ISSUE THREAD

**Issue by captify-mgruau** [WICG/attribution-reporting-api#1084]
We need to be able to implement attribution-src="https://www.ourattributionurl.com/" either as HTML or as JavaScript, however neither of these are possible using Third Party Tags adserved from external sources such as DCM. 

To my understanding, there is an issue with Google's Same Origin Policy which prevents us from modifying the contents of an iframe. This is because the origin site is different to the site where the code is implemented to add the attribution source. Basically, if the iframe is coming from DCM, and the code is being run on a DSP, it won't append the HTML or modify the click request with JS because it can't access the iframe.

Since most DSPs don't support adding an entire click/impression tag as HTML, we also can't edit the tags to include the source. In fact with most 3rd party hosted tags such as DCM tags, the click and impression URLs are added on the client side, so we can't even see them within the tag to edit them. Here is example DCM tag for illustration:

```
<script type="text/adtag">
<ins class='dcmads' style='display:inline-block;width:728px;height:90px'
    data-dcm-placement='N892624.2245506CAPTIFY/B29704276.364693446'
    data-dcm-rendering-mode='script'
    data-dcm-https-only
    data-dcm-ltd='false'
    data-dcm-resettable-device-id=''
    data-dcm-app-id='' data-dcm-click-tracker='${CLICK_URL}'>
  <script src='https://www.googletagservices.com/dcm/dcmads.js'></scr+ipt>
</ins>
</script>
```

In the above case, the only access we have to either the click or impression tracker is via the data-dcm-click-tracker value which can only pass a URL, so we're not able to modify this to include the parameter either.

Many DSPs, including Google's DV360, don't allow the user to implement overriding click or impression tracking HTML on this tag type either, so we can't grab the tracker from the client tag and then re-implement it on our side with an attribution source.

Is there a workaround we can implement to make this work?

**Comment by dmdabbs** [comment]
See also this issue the ARA team closed because it wasn't strictly related ot ARA:
https://github.com/WICG/attribution-reporting-api/issues/701.

Probably this should be an issue with the DCM team if they have an issue system.

**Comment by captify-mgruau** [comment]
Thanks @dmdabbs, yes it's a duplicate of #701. I'll chime in on this issue since we're now at a stage where the rubber meets the road. Adoption of ARAPI will be severely restricted if we don't solve for DCM adopting it so I don't think we can limit ourselves to say this is not an ARAPI problem at the core.

**Comment by captify-mgruau** [comment]
Duplicate of #701
