### ISSUE TITLE
Cross App and Web Attribution reporting - sdk

### ISSUE THREAD

**Issue by roistaboola** [WICG/attribution-reporting-api#1106]
the use case in reference has the SDK (at the publisher app) presenting the Ad and calling the **OS** android API registerSource(register source end point url).
that request is successful as the API does send an http request to the and the register source end point.

The Ad is then presented at the **Web** browser on the advertiser site page where our 3p script send http impression logs.
The logs http request were added the attribution request & response headers as follows::

request headers:
Attribution-Reporting-Eligible: trigger
Attribution-Reporting-Support: os, web

response headers:
Attribution-Reporting-Support: os, web
Attribution-Reporting-Register-OS-Trigger: register trigger end point url
    
Though all permissions were set at the browser:
Chrome Version is 119, Privacy Sandbox Ads API was enabled (chrome://flags)

The browser did not send a request to the register trigger end point url
**1. what should be done for the browser to send a request to the URL defined at Attribution-Reporting-Register-OS-Trigger ?**

Have also registered to Registration for the Cross App and Web Attribution Measurement trial with these values:
Third Party: Yes
Origin: the script web origin

Have added the method defined at 
https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#16-can-i-provide-tokens-by-running-script
to the 3p script (that send the http request with the attribution related headers).

The browser still did not send a request to the <register trigger end point url>
**2. is that the expected use of the Token ? can the Token be added to the header ?  what should be done for the browser to send a request to the URL defined at Attribution-Reporting-Register-OS-Trigger  ?**

**Comment by linnan-github** [comment]
@roistaboola Thanks for the feedback. The `Attribution-Reporting-Register-OS-Trigger` header is empty in the response,  could you please try to validate the response you set with the header validator? Thanks.
https://wicg.github.io/attribution-reporting-api/validate-headers

**Comment by roistaboola** [comment]
Hi, have updated the case. 
The Attribution-Reporting-Register-OS-Trigger header value was the register trigger end point url such as the following:
https://hostname.com/trigger?conv_id=18

**Comment by linnan-github** [comment]
@roistaboola Has the host completed the enrollment process? https://github.com/privacysandbox/attestation/blob/main/how-to-enroll.md

If not, for testing, this can be overridden with chrome://flags/#privacy-sandbox-enrollment-overrides

**Comment by linnan-github** [comment]
Given that this is an implementation issue, please consider re-filing at https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/new/choose by selecting the "Attribution Reporting API" question.

**Comment by roistaboola** [comment]
Hi, given the focus is specific to 'Cross App and Web Attribution reporting', can i continue at the current thread ? 
can the questions  #1 and #2 at the start of the thread be addressed ? thanks
