### ISSUE TITLE
measurementManager.registerSource Invalid scheme for app destination: https; dropping the source

### ISSUE THREAD

**Issue by roistaboola** [WICG/attribution-reporting-api#1130]
Hi, 
A register source endpoint had been defined at https://the_host_uri/endpoint_path?parameters

calling the registerSource attribution API as follows, 
measurementManager.registerSource(attributionSourceUri, null, mCallback );

generated the exception:
2023-12-17 13:45:57.413 17656-17690 adservices  com.google.android.adservices.api    E  **Invalid scheme for app destination**: https; dropping the source.

at times, this error is written as well: 
AndroidRuntime com.google.android.adservices.api FATAL exception:
java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection at com.android.adservices.service.measurement.MeasurementHttpClient.setup(MeasurementHttpClient.java:63) at com.android.adservices.service.measurement.registration.AsyncSourceFetcher.openUrl(AsyncSourceFetcher.java:705) 

Please note: 
1. the sdk project and taboola trc server are using javax.net.ssl.HttpsURLConnection
2. the request to the end point service is successful if sent from postman.
3. in case the endpoint service is a postman mock server, there is no error and registerSource is sent to the mock server.

I'd like to ask what is blocking the request from being sent to the actual endoint (not the mock server) and how it can be resolved. 
Thanks !

**Comment by apasel422** [comment]
Thanks for the report. Unfortunately this repository is concerned with the Attribution Reporting API specification itself, not Android-specific user questions. Please consider re-filing your issue in [the Android public tracker](https://b.corp.google.com/issues/new?component=1116743&template=1629474).
