### ISSUE TITLE
Flex event explainer doesn't describe how attribution-success debug reports are affected

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#1144]
https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#attribution-success-debugging-reports

**Comment by evazkj** [comment]
Similarly, for flex events, if value bucketing is enabled, what will the "trigger_data" field in the report become? ( I guess it will be set to null?)

**Comment by apasel422** [comment]
> Similarly, for flex events, if value bucketing is enabled, what will the "trigger_data" field in the report become? ( I guess it will be set to null?)

The `trigger_data` field in the report will always correspond to whatever `trigger_data` was used to match against the source, regardless of whether custom summary buckets are being used.

**Comment by evazkj** [comment]
Is it possible that for a certain report with value bucketing, multiple triggers contribute to it, but they have different trigger data?
for example, a trigger_spec with `trigger_data: [0, 1]'`, then triggers with data = 0 or 1 will al contributing to a report, right?

**Comment by apasel422** [comment]
> Is it possible that for a certain report with value bucketing, multiple triggers contribute to it, but they have different trigger data?

No, the Flexible Event summarization is always performed per `trigger_data`.

**Comment by evazkj** [comment]
I see. Thanks for the clarification.

**Comment by evazkj** [comment]
One other question, not related to OP, according to https://github.com/WICG/attribution-reporting-api/blob/main/ts/src/flexible-event/main.ts#L96 , `num_buckets` has to be same as `num_reporting_window`, I didn't see an explanation for it.

**Comment by apasel422** [comment]
> One other question, not related to OP, according to https://github.com/WICG/attribution-reporting-api/blob/main/ts/src/flexible-event/main.ts#L96 , `num_buckets` has to be same as `num_reporting_window`, I didn't see an explanation for it.

That may just be a command-line-invocation requirement. I suggest trying out a sample registration using the [header validator](https://wicg.github.io/attribution-reporting-api/validate-headers?header=source&json=&source-type=event&flex=true) to test your exact configuration is supported.

**Comment by apasel422** [comment]
Closing in favor of a new issue since the conversion got a bit sidetracked here.
