### ISSUE TITLE
Provide API measurement platform preference while registering sources and triggers 

### ISSUE THREAD

**Issue by khantilchoksi** [WICG/attribution-reporting-api#1148]
Currently, Ad-techs (reporting endpoint) determines the availability of OS-level support based on the `Attribution-Reporting-Support` containing `OS` presence. 

There certain scenarios where `Attribution-Reporting-Support` is unavailable, for example pre-existing conversion tags which do not include the `attributionsrc` attribute. 

Provide a support in `Attribution-Reporting-Register-Source` and `Attribution-Reporting-Register-Trigger` for **`preferred-platform`** as:

e.g. `Attribution-Reporting-Register-Source` would look like 
```
 {
  "preferred_platform": "os" (possible values: web or os)

  "register_os_source": [ 
        { "reporting_endpoint":  "https://adtech.example/register", 
           "debug_reporting": true
        },
        { "reporting_endpoint":  "https://other-adtech.example/register", 
           "debug_reporting": true
        },
     ]

 // Already existing fields in `Attribution-Reporting-Register-Source`
 "destination": "[eTLD+1]",
  "source_event_id": "[64-bit unsigned integer]",
  "expiry": "[64-bit signed integer]",
  "priority": "[64-bit signed integer]",
}
```

Few advantages:
- This way, Ad-techs can prefer to register using one API over the other, whenever available.
- Defer the API platform choice decision to Chrome client / Privacy Sandbox API.
- This would also reduce overhead of sending yet another response header `Attribution-Reporting-Register-OS-Source`.

**Debugging Support:**  Respond with `os-source|trigger-delegated` `success` or `failure` response if the delegation to OS-level was performed or not. 

FYI, current behavior of the API seems to be when reporting endpoint returns with both `Attribution-Reporting-Register-Source|Trigger` and `Attribution-Reporting-Register-OS-Source|Trigger`, the source and trigger is rejected.

**Comment by apasel422** [comment]
> FYI, current behavior of the API seems to be when reporting endpoint returns with both `Attribution-Reporting-Register-Source|Trigger` and `Attribution-Reporting-Register-OS-Source|Trigger`, the source and trigger is rejected.

Yes, that is intentional.
