### ISSUE TITLE
Epsilon param configuration

### ISSUE THREAD

**Issue by kamalonly** [WICG/attribution-reporting-api#1165]
It is documented that "consider the ability to tweak epsilon as temporary". Does it mean that in future epsilon value will be fixed and can not be configured by ad techs?

**Comment by akashnadan** [comment]
@kamalonly  Just to confirm, are you referring to event-level reporting epsilon or summary report epsilon that can be configured in aggregation service?

For summary report epsilon, the current epsilon value can be configured by ad-techs up to a predetermined threshold, which is currently 64.  We plan to keep the epsilon configuration as a range. Additionally, we recommend testing different epsilon values and identifying inflection points for your own use-cases and providing feedback. If there are any future changes to the range of epsilon values, we will make sure to communicate to ad-techs in advance.

**Comment by apasel422** [comment]
Feel free to reopen if the above comment didn't answer your question.
