### ISSUE TITLE
Using `attributionsrc` in window.open() without popup

### ISSUE THREAD

**Issue by tomhnzhou** [WICG/attribution-reporting-api#1196]
Specifying `attributionsrc` in window.open() has the side effect of [opening a popup window](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#popup), which is not the desired behavior. 

This is our current setup before adding `attributionsrc`:

`window.open(
    url,
    "_blank",
    "noopener");`

Is there any workaround such that we can add `attributionsrc` without requesting a popup? Thanks!

**Comment by apasel422** [comment]
@tomhnzhou Could you provide the code you are using *with* `attributionsrc`?

**Comment by apasel422** [comment]
If I understand correctly, you can set [`popup=0`](https://html.spec.whatwg.org/multipage/nav-history-apis.html#popup-window-is-requested) in your `window.open` features.

**Comment by apasel422** [comment]
@tomhnzhou Did the suggestion in https://github.com/WICG/attribution-reporting-api/issues/1196#issuecomment-2002610955 work for you?

**Comment by apasel422** [comment]
Feel free to reopen if this didn't solve the issue.
