### ISSUE TITLE
Consider allowing the destination limit to favor new sources

### ISSUE THREAD

**Issue by johnivdel** [WICG/attribution-reporting-api#1228]
The [max destinations for unexpired sources limit](https://wicg.github.io/attribution-reporting-api/#max-destinations-covered-by-unexpired-sources) is currently spec'd such that:

once a publisher site registers sources for 100 different destinations, all subsequent source registrations will fail

Registrations will fail until these sources expire or until they are attributed. This has the downside that it locks out registration on a site.

We may want to consider, instead of blocking new sources, to kick out old sources to make space. This could be done by formulating this limit as a FIFO queue.

**Comment by giladbarkan-github** [comment]
Could we please detail the privacy concern this limit addresses?
