### ISSUE TITLE
Aggregatable flexible contribution filtering

### ISSUE THREAD

**Issue by agarant** [WICG/attribution-reporting-api#1291]
The Private Aggregation API and the Aggregation Service added support for[ more flexible contribution filtering using filtering ids](https://github.com/patcg-individual-drafts/private-aggregation-api/blob/main/flexible_filtering.md).

This functionality can also be useful in the context of the Attribution Reporting API; the [presented use cases](https://github.com/patcg-individual-drafts/private-aggregation-api/blob/main/flexible_filtering.md#use-case-examples) are also applicable to ARA.

**Comment by santurak1** [comment]
@santuraki foundation Ai, 😂
