### ISSUE TITLE
Consider using duration strings for attribution expiry

### ISSUE THREAD

**Issue by jyasskin** [WICG/attribution-reporting-api#132]
The `<time>` element accepts a duration format parsed by https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#parse-a-duration-string. It might be more ergonomic to accept the same format in the new `<a attributionexpiry>` attribute in this spec, rather than the Javascript-centric number of milliseconds.

**Comment by apasel422** [comment]
@johnivdel This does seem more ergonomic, especially since I can't see the value in millisecond precision for this field.

**Comment by johnivdel** [comment]
Agreed on the points above. 

To go a step further, I wonder if we could just accept expiry as an integer number of days.

The View explainer requires expiries to be rounded to the nearest (whole day)[https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_views.md#coarse-attribution-expiry]. While clicks do not have quite the same privacy properties, it's hard to judge if the additional granularity gives sufficient utility to justify both the input format complexity and the complexity when handling "bad" inputs.

cc @csharrison @maudnals

**Comment by csharrison** [comment]
We chose this by following the advice in https://w3ctag.github.io/design-principles/#milliseconds. I'm OK with something more ergonomic but I think we should consider filing a bug on TAG if the advice is generally applicable.

**Comment by jyasskin** [comment]
+1 for filing an issue against the design principles to see if the TAG wants to take a stance one way or the other.

**Comment by csharrison** [comment]
It looks like milliseconds might not have been the right choice. Especially now that we may be moving to response-based registration we should try to match other header-based APIs for time format. I see two alternatives:

1. Delta seconds (caching, Age, Retry-After)
2. [HTTP-Date](https://httpwg.org/specs/rfc7231.html#http.date) (Retry-After)

It seems like Retry-After uses both delta-seconds and http-dates. I am not sure which is more standard for new HTTP-based APIs but given that these will likely be embedded in JSON or similar structure, I am inclined to use the simpler format and go with seconds.

**Comment by csharrison** [comment]
From the advice we got from the TAG discussion, we aligned on delta-seconds as our duration encoding.
