### ISSUE TITLE
Header validator inconsistent with spec re size checks 

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#1321]
Per https://wicg.github.io/attribution-reporting-api/#parse-attribution-destinations, the size of the `destination` field is supposed to be checked after URL-to-site transformation and deduplication, but the validator checks the size of the JSON list itself, causing some registrations that would be allowed by the spec to be prohibited by the validator.

This also applies to [`filter_data` values](https://wicg.github.io/attribution-reporting-api/#parse-filter-data).

**Comment by gauche-torres** [comment]
- se agradece mucho
