### ISSUE TITLE
Incorrect Laplace noise formula in your documentation

### ISSUE THREAD

**Issue by TedTed** [WICG/attribution-reporting-api#1329]
From https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#differential-privacy:

> noise distributed according to Laplace(epsilon / L1) should achieve epsilon differential privacy

You probably meant "Laplace(L1 / epsilon)" here. I assume the code is doing the right thing ([this page](https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/understanding-noise#how-noise-is-applied) is correct) but I haven't checked.

**Comment by csharrison** [comment]
Thanks, yes this is a typo!
