### ISSUE TITLE
Verifying Subdomain Conversion in Source Registration Tests

### ISSUE THREAD

**Issue by Dhiego777** [WICG/attribution-reporting-api#1350]
Good afternoon, we are doing a test and the request "/register-source?lineItemId=0&creativeId=138480547844&destination=https://ads.uol.com.br/" has the header with the destination "https://ads.uol.com.br", but when checking the json in the source registrations, located in "chrome://attribution-internals/", the destination is as "destination": "https://uol.com.br".
We would like to know how we can check the conversion of subdomains in the case of "https://ads.uol.com.br"?

Below is the source header and the print of the source and trigger.
Source Registrations:

```
{
    "source_event_id": "1719498091940",
    "destination": "https://ads.uol.com.br",
    "expiry": 2592000,
    "event_report_window": 3600,
    "priority": "0",
    "aggregation_keys": {
        "conversionCount": "0x203e14ab93"
    },
    "aggregatable_report_window": "86400",
    "filter_data": {
        "creativeId": [
            "138480495507"
        ]
    },
    "debug_key": "647775351539539",
    "debug_reporting": true
}
```
![image](https://github.com/WICG/attribution-reporting-api/assets/70820502/ef97397c-ea17-4e18-84a7-005d7f63b8f3)

Trigger Registrations
![image](https://github.com/WICG/attribution-reporting-api/assets/70820502/ddd52797-1502-4aac-beea-83be069e1e04)

**Comment by apasel422** [comment]
[Here is a link](https://wicg.github.io/attribution-reporting-api/validate-headers?header=source&json=%7B%0A++++%22source_event_id%22%3A+%221719498091940%22%2C%0A++++%22destination%22%3A+%22https%3A%2F%2Fads.uol.com.br%22%2C%0A++++%22expiry%22%3A+2592000%2C%0A++++%22event_report_window%22%3A+3600%2C%0A++++%22priority%22%3A+%220%22%2C%0A++++%22aggregation_keys%22%3A+%7B%0A++++++++%22conversionCount%22%3A+%220x203e14ab93%22%0A++++%7D%2C%0A++++%22aggregatable_report_window%22%3A+%2286400%22%2C%0A++++%22filter_data%22%3A+%7B%0A++++++++%22creativeId%22%3A+%5B%0A++++++++++++%22138480495507%22%0A++++++++%5D%0A++++%7D%2C%0A++++%22debug_key%22%3A+%22647775351539539%22%2C%0A++++%22debug_reporting%22%3A+true%0A%7D&source-type=event&flex=false) to our header validator with your registration JSON.

Note the warning:

> ["destination"] URL components other than site (https://uol.com.br) will be ignored

**Comment by dmdabbs** [comment]
The explainer covers it also.

>`destination`: Required. An origin whose [site](https://html.spec.whatwg.org/multipage/browsers.html#site) is where attribution will be triggered for this source. The field may also be specified as a list (JSON array) of no more than three elements.

As I understand it, if you trigger a conversion on "https://uol.com.br/" _or any origin under that site_, ARA should be able to perform the attribution to your example source.
