### ISSUE TITLE
<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>

### ISSUE THREAD

**Issue by Saeedazimi69** [WICG/attribution-reporting-api#1354]
https://calendly.com/jay_raj_ninjatech/30min

**Comment by Saeedazimi69** [comment]
Wallet

**Comment by apasel422** [comment]
Stop spamming this repository.

**Comment by danielnovais-tech** [comment]
<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
