### ISSUE TITLE
Consider omitting Attribution Reporting request headers when there is none attribution support

### ISSUE THREAD

**Issue by linnan-github** [WICG/attribution-reporting-api#1368]
Currently when there is none attribution support (neither web nor os), the `Attribution-Reporting-Eligible` header may still be sent and `Attribution-Reporting-Support` header is also sent as empty. We may consider omitting both to reduce bandwidth and a better indicator that the request is not eligible for Attribution Reporting.

**Comment by dmdabbs** [comment]
Sending all GREASED values would signal "nothing" without sending nothing, though wouldn't address fingerprinting concern.

**Comment by apasel422** [comment]
> Sending all GREASED values would signal "nothing" without sending nothing, though wouldn't address fingerprinting concern.

Yes, the header would still be subject to greasing.

**Comment by linnan-github** [comment]
> So it might be beneficial to tell the reporting origin that it is eligible for nothing, as opposed to letting it assume it can still register triggers.
> 
> But it depends on whether we consider the presence/absence/value of these headers to be a fingerprinting surface.

Agreed that it may be beneficial in this aspect to distinguish these two cases. As for the fingerprinting, I think it's already true for requests with `Attribution-Reporting-Support` header, so should be fine, at least not regression.
