### ISSUE TITLE
Non valid reports of type "trigger-unknown-error"

### ISSUE THREAD

**Issue by Fatima-EzzahraFettah** [WICG/attribution-reporting-api#1389]
100% of our “trigger-unknown-error” reports received over the past month are non valid reports (the body messages of this report type do not include the mandatory source attributes in addition to the parameter “limit”), not respecting the [documentation](https://github.com/WICG/attribution-reporting-api/blob/main/verbose_debugging_reports.md#report-data).

- I wanted to see if you are aware of the issue, maybe the documentation needs some update.

**Comment by apasel422** [comment]
Thanks for pointing this out.

[Per the specification](https://wicg.github.io/attribution-reporting-api/#obtain-verbose-debug-data-body-on-trigger-registration), there is no *requirement* for other fields to be present in the report body for `trigger-unknown-error`, but you are right that [the table](https://github.com/WICG/attribution-reporting-api/blob/main/verbose_debugging_reports.md#report-data) describing fields in the report body is potentially misleading, as the source-related fields may or may not be present depending on the underlying cause of the error. For example, an internal error could occur before the source-matching logic happens, which would mean that no source data is available to populate the debug report with.

I will update the documentation to be more clear about this. We should probably replace the ❌ and ✓ with required/optional/absent.
