### ISSUE TITLE
Enrollment Id Not Found for Registration URI: https://trc.taboola.com/ 

### ISSUE THREAD

**Issue by roistaboola** [WICG/attribution-reporting-api#1492]
Hi, 

Using Pixel8Pro API Level 35 (VanillaIceCream) Emulator,

with the following setting at the ad_services_config.xml of installed SDK:
<attribution allowAdPartnersToAccess="<the enrollment id value that at https://taboola.com/.../privacy-sandbox-attestations.json>" allowAllToAccess="false" />

and these settings at the privacy-sandbox-attestations.json:

"enrollment_id": "<the enrollment id>",
      "enrollment_site": "https://taboola.com/",
      "platform_attestations": [
        {
          "platform": "chrome",
          "attestations": {
            "attribution_reporting_api": {
              "ServiceNotUsedForIdentifyingUserAcrossSites": true
            },
            "topics_api": {
              "ServiceNotUsedForIdentifyingUserAcrossSites": true
            },
            "protected_audience_api": {
              "ServiceNotUsedForIdentifyingUserAcrossSites": true
            }
          }
        },
        {
          "platform": "android",
          "attestations": {
            "attribution_reporting_api": {
              "ServiceNotUsedForIdentifyingUserAcrossSites": true
            },
            "topics_api": {
              "ServiceNotUsedForIdentifyingUserAcrossSites": true
            },
            "protected_audience_api": {
              "ServiceNotUsedForIdentifyingUserAcrossSites": true
            }
          }
        }
      ]
    },

**Enrollment had failed**, with following reported at the logcat :
Enrollment check failed, Reason: Enrollment Id Not Found, Registration URI: https://trc.taboola.com/attribution-reporting/attribution_source?destination=..

Please advise as to what could resolve the enrollment check failure. thanks.

**Comment by roistaboola** [comment]
note that the site at privacy-sandbox-attestations.json is
"enrollment_site": "https://**taboola.com**/",

whereas the registerSource request was sent to https://**trc.taboola.com**/attribution-reporting]

is that an issue ? as i understand everything that ends with "taboola.com" should work.
isn't that right ?

**Comment by apasel422** [comment]
Thanks for the report. Please re-file this issue at https://github.com/privacysandbox/privacy-sandbox-dev-support.

**Comment by roistaboola** [comment]
Hi [apasel422](https://github.com/apasel422)
Have opened this issue at https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/456 
There is no comment there, also i see there are very few issue reported at that inventory.
why can the issue i opened be handled at this repository where all other ARA issue are handled ? 
can you please attend to the question itself ? thanks

**Comment by apasel422** [comment]
> why cant the issue i opened be handled at this repository where all other ARA issue are handled ?

Your question relates to a Chrome/Android-specific configuration problem, not to the Attribution Reporting API itself.
