### ISSUE TITLE
Document differences from ad-click-attribution

### ISSUE THREAD

**Issue by jyasskin** [WICG/attribution-reporting-api#155]
The explainer links to https://github.com/WICG/ad-click-attribution as an alternate way of achieving some of the same use cases, but I don't see an explanation of what's different in this proposal or why it's useful to [users, etc.](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies) to differ. That would probably fit in a [considered alternatives](https://w3ctag.github.io/explainers#considered-alternatives) section, either inline or behind a link.

**Comment by csharrison** [comment]
Looks like this is now being tracked and discussed in #866 . Let me close this issue.
