### ISSUE TITLE
Consider sending aggregate error reports for event-level reports

### ISSUE THREAD

**Issue by johnivdel** [WICG/attribution-reporting-api#160]
There are a number of failure modes which can be difficult to observe due to the delayed reporting mechanism, and opaque way the browser handles sources and triggers for event level reports.

Some examples are:

- a source declares the wrong `attributiondestination`, causing the browser to drop the source
- a given user hits the [report rate limit](https://github.com/WICG/conversion-measurement-api#triggering-attribution-multiple-times-for-the-same-source), causing all subsequent reports to not be sent in the time period
- a source is removed due to the [pending destination limit](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting.md#limiting-the-number-of-unique-sites-covered-by-pending-sources)

In these cases, there is no straight-forward way for a developer to monitor this behavior outside of inferring they aren't receiving as many reports as they would normally.

It's possible the API could proactively send reports for these types of errors in parallel. To prevent cross-site information from being revealed the browser could send very little information in the error reports, for example just revealing {reporting_origin,error_code}.

It could also be possible to create and send the error reports similar to [aggregate reports](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md).

**Comment by maudnals** [comment]
A few other cases raised in the 6/28 [meeting](https://github.com/WICG/conversion-measurement-api/tree/main/meetings)
* Tag is misconfigured
* The endpoint fails
*  ...

**Comment by maudnals** [comment]
Note: in Chrome, local debugging is partly supported:
- Issues (console warnings) are thrown for a number of developer errors
- A debugging UI is available at chrome://conversion-internals

What remains uncovered is the "at-scale" aspect: how to detect what's going wrong in prod / for end-users?
