### ISSUE TITLE
Masked LARK proposal for model training

### ISSUE THREAD

**Issue by erik-anderson** [WICG/attribution-reporting-api#181]
Microsoft just published a proposal called [Masked Learning, Aggregation and Reporting worKflow (Masked LARK)](https://github.com/WICG/privacy-preserving-ads/blob/main/MaskedLARK.md).

As the name implies, the proposal uses aggregate reporting with a focus on enabling better training of ML models. I'm sure there will be conversation involving #157 as we compare and contrast the proposals. Given the overlap, I wanted to make sure we provided a pointer here in the form of an issue.

We'd be happy to present on the proposal at a high-level during the regularly scheduled Conversion Measurement calls, taking questions and feedback via issues in the repo the proposal lives in, as well as engaging with folks on this issue specifically.

**Comment by csharrison** [comment]
Hey Erik, thanks for posting this. Would you be willing to present on this in our next call?

**Comment by erik-anderson** [comment]
Yes, we can present on this on Monday.

**Comment by erik-anderson** [comment]
Thanks to @dxcharles for leading the presentation today. We've made a [copy of the slides](https://github.com/WICG/privacy-preserving-ads/blob/main/presentations/20210726%20-%20Masked%20LARK%20presentation.pdf) available in our repo. I also placed a link in the minutes doc.
