### ISSUE TITLE
Consider the case of the same priority in event and navigation

### ISSUE THREAD

**Issue by shigeki** [WICG/attribution-reporting-api#212]
For example, in the case of `<a attributionsourceeventid="998" attributiondestination="https://example.jp" registerattributionsource href="https://example.jp/">Ad View and Click</a>` , both source type event(view) and navigation(click) have the same priority.

Usually, a user clicks the ad after viewing and makes an attribution. Then Chrome will report the navigation type because the navigation has a newer time than the view event. It has no issue.

But when the user views the ad again after the ad clicking and makes an attribution, Chrome will send the event type report at this time.

We expect that the source type of navigation should have a higher priority than that of the event. In this case, we have a workaround to use JS API with a lower priority for the view-through event. Still, we should consider giving precedence to the navigation rather than a simple time comparison when they have the same priority.

**Comment by csharrison** [comment]
This seems like a pretty reasonable default behavior to me. Let's bring this up in the next call to see if others agree. cc @johnivdel

**Comment by apasel422** [comment]
It is no longer possible for anchor tags to register event sources.
