### ISSUE TITLE
Is Chrome planning to use JS API to replace pixel redirects for conversion registration?

### ISSUE THREAD

**Issue by minghaocwang** [WICG/attribution-reporting-api#22]
Hi,
In this issue: https://github.com/WICG/ad-click-attribution/issues/31, John Wilander mentions to use a  Modern Triggering of Ad Click Attribution technique (a new Javascript API) to replace legacy pixel redirects for signaling conversion. I am wondering will Chrome team follow the similar direction? If so, whats the plan and details for this JS API?

**Comment by johnivdel** [comment]
As @csharrison noted in [this comment](https://github.com/WICG/ad-click-attribution/issues/31#issuecomment-567556076), I don't think there are issues with implementing a JS equivalent alongside the [pixel redirect](https://github.com/csharrison/conversion-measurement-api#conversion-registration). 

As far as the JS API completely replacing conversion redirects, the linked comment touches on avoiding the need for third-party scripts to be included on sites for conversion registration. I think we also have to be careful in understanding the breakage of existing conversion measurement solutions across the web if the pixel redirect was not supported.

With that, potential designs will need to be fleshed out more on WICG/ad-click-attribution#31 before there are any plans/details for the JS API.

**Comment by csharrison** [comment]
See our explainer for the current mechanism for firing attribution triggers / conversions:
https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md
