### ISSUE TITLE
Consider batching reports for the same source in the same reporting window

### ISSUE THREAD

**Issue by johnivdel** [WICG/attribution-reporting-api#227]
Currently, if a clicked source generates 3 reports in the same reporting window, the browser will issue 3 separate post requests to the reporting endpoint in a random order.

To save bandwidth and pre-join these reports for reporting endpoints, we could consider modifying the report body to contain an array of reports.

Because these are already join-able server-side this shouldn't have any privacy implications. This will add a small amount of complexity to the report body however.

**Comment by apasel422** [comment]
A more updated example:
```jsonc
{
  "attribution_destination": "https://destination.test",
  "scheduled_report_time": "123",
  "source_type": "navigation", // or "event"
  "source_event_id": "456",
  "reports": [
    {
      "randomized_trigger_rate": "...",
      "report_id": "...",
      "trigger_data": "1"
    },
    {
      "randomized_trigger_rate": "...",
      "report_id": "...",
      "trigger_data": "7"
    }
  ]
}
```

**Comment by csharrison** [comment]
Closing as not planned for now.
