### ISSUE TITLE
Multiple pixels / ROI optimization

### ISSUE THREAD

**Issue by ALamraniAlaouiScibids** [WICG/attribution-reporting-api#230]
I am following up the presentation of 09/21 meeting.

In order to be able to do campaign optimization, a reporting API would also need to report on different pixels.
Indeed, there are many use cases where we don’t have enough final conversions (for instance buying a car online) and we would need to use "intermediate information" (“add to cart” or “visit” information).
Also the API would need to provide enough information on the "conversion" to allow for ROI optimization  (return on interest) where conversion has a value represented by a float number (for instance the revenue generated).

Having 1 bit of data for the Post View conversion use case (and 3 bits for Post Click conversion) would not be enough to support optimizing in these use cases.

**Comment by csharrison** [comment]
Thanks for filing Lamrani. I agree doing ROI optimization is hard in the event-level API. I think the current best thing you could do is use a combination of event-level and aggregate data for this use case (e.g. tune a pcvr model with aggregate data). This is a great area for future investigation.

For the multiple pixel case, does adding a conversion priority help, so at least you can learn the most valuable part of the funnel the user went through (e.g. using [trigger priority](https://wicg.github.io/conversion-measurement-api/#ref-for-attribution-report-trigger-priority))?
