### ISSUE TITLE
Questions about app-to-web support

### ISSUE THREAD

**Issue by ycmou** [WICG/attribution-reporting-api#239]
Hello! Regarding the [app-to-web proposal ](https://github.com/WICG/conversion-measurement-api/blob/main/app_to_web.md), I have a few questions on what type of scenarios are planned (or feasible) to be supported. (Keep in mind I'm not an Android engineer so may be missing some basic context. Please correct me as needed!)

Currently the goals in the app-to-web explainer includes: 
- Support measurement of ads that show up within apps that later convert in the browser
- Support measurement of ads within embedded webview that later convert in the browser

What is the "browser" that would be supported here? 

Specifically there are two scenarios we are considering:
1. Our Android app uses Chrome Custom Tabs for its in-app browsing experience. Will there be attribution + reporting support for CCT?
2. Most of our users view/tap through ads within our app, but then convert later within their native in-app browser (e.g. mobile Chrome app). Would this "app-to-mobile-web-browser" flow supported?

**Comment by csharrison** [comment]
cc @mthiesse. The browser is configurable by the calling app. In the example code we just use the default browser.

1. CCT works just like a Chrome tab so it should work just like if the user was browsing in Chrome.
2. Yes that should be supported

**Comment by maudnals** [comment]
@csharrison Maybe we could update the explainer to include this?
I opened a PR here: https://github.com/WICG/conversion-measurement-api/pull/263/files
cc @ycmou

**Comment by mthiesse** [comment]
The language "conversion within a native in-app browser" is probably too general as we don't support webview yet? Maybe something like:
"Ad view/tap within a native Android app, conversion within a custom tab provider (e.g. Chrome Custom Tabs)."

**Comment by mthiesse** [comment]
Oh, nevermind, this is aspirational :)

**Comment by mthiesse** [comment]
Actually I'm not sure if this is aspirational or describing what we can do with the current API. The goals section states "Support measurement of ads within embedded webview that later convert in the browser", which is only partially true currently. If the webview is just displaying an ad and clicking that ad takes you to the browser, this API covers that use case. However, if you're using webview as an in-app browser and an ad click stays within the webview, that's not currently covered by this API.

**Comment by cedelman** [comment]
Hi @maudnals could you clarify whether app-to-web attribution API is still in a proposal state, available today, or releasing soon along with the Attribution Reporting API web-to-web?
