### ISSUE TITLE
Consider using response headers for source registration instead of individual attributes

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#261]
### Overview

Using headers has a number of benefits. The browser needs a way to associate the network request and response header with the API performing the navigation (anchor element, `window.open`).

One idea is to add a new attribute `attributionsrc` that allows the browser to create a request that is strongly associated with the invocation of the API performing the navigation. This was brought up [previously](https://github.com/WICG/conversion-measurement-api/blob/0b7446a3d4f458cd997df76ec93afe69a4babe4b/meetings/2021-07-12-minutes.md).

When an anchor is clicked that specifies `attributionsrc`, or when `window.open` is called with an `attributionsrc`, the browser will create an attribution registration request which is a background "keepalive" request managed by the browser. The browser will make the initial request and follow all redirects.

When the `registerattributionsource` attribute is added to an anchor that specifies `attributionsrc`, or when `window.attributionReporting.registerAttributionSource()` is called, the browser will create a request as well.

The browser will process a `Register-Attribution-Source` response header on these types of requests. This response header is a structured dictionary header which contains all attribution source parameters:

```http
Register-Attribution-Source: sourceeventid=..., destination=..., expiry=..., ...
```

When this header is present, the browser will create an attribution source with the specified parameters, a reporting origin matching the origin that sends the header, and a source origin matching the origin of the top-level page the request was initiated on.

### Examples

Anchor clicks:
```html
<a href="https://advertiser.example/landing" attributionsrc="https://adtech.example/attribution_source?my_ad_id=123">click me</a>
```

`window.open`:
```js
window.open("https://advertiser.example/landing", "_blank", "attributionsrc=https://adtech.example/attribution_source?my_ad_id=123")
```

Anchor views:
```html
<a href="https://advertiser.example/landing" attributionsrc="https://adtech.example/attribution_source?my_ad_id=123" registerattributionsource></a>
```

JS view API:
```js
window.attributionReporting.registerAttributionSource("https://adtech.example/attribution_source?my_ad_id=123");
```

App-to-web intent:
```java
Intent convIntent = new Intent("android.web.action.APP_ATTRIBUTION");
Bundle innerBundle = new Bundle();
innerBundle.putString("attributionsrc", "https://adtech.example/attribution_source?my_ad_id=123");
```

### Allowing multiple reporters for one click

Currently, only one reporting endpoint may register impressions for a given navigation in the API.

We could potentially allow redirects within the attribution request to each specify their own `Register-Attribution-Source`.

This allows different adtechs with visibility into other impressions to measure conversion events with different scopes (discussed briefly [previously](https://github.com/WICG/conversion-measurement-api/blob/main/meetings/2021-10-18-minutes.md)).

For attribution registration requests made from anchor clicks or `window.open`, the browser will verify that the attribution destination matches the navigation destination.

For attribution registration requests from views, the browser will require all attribution destinations to match the attribution destination of the first attribution source. This has the nice side effect that a single `attributionsrc` only counts once against the pending destination limit for views no matter how many third parties are present in the chain.

### Pros

- Security: By using a header mechanism, reporting origins will have direct control over whether an attribution source is registered in their scope. Previously this was not possible, but theoretically possible when layered with a fraud-prevention mechanism. This partially mitigates concerns about fraud, as with this change a genuine browser will never register a source without the reporting origin’s opt-in.
- Maintainability: Adding a new parameter, e.g. source priority, only entails updating server-side logic.
- May support multi-registration, which is not possible with the existing anchor API without significant changes.
- This proposal lends itself better to some of the surfaces being discussed in #194: JSON may make more sense returned in a header/response body than in an HTML attribute.

### Cons

- This approach increases bandwidth in comparison to the declarative API, as every source registration will result in an additional HTTP request.

### Alternatives

Rather than limiting header processing to `attributionsrc` requests, the browser could process the header on all subresource requests.

Today, there are a number of places where impressions can be registered just by having an `img` tag on the page, similar to conversions.

This would allow these existing pings to also register "event" (view)  attribution sources:

```html
<img src="adtech.example/register-impression">
```

**Comment by csharrison** [comment]
If `attributionsrc` is declared with no value, I proposed we set the value to equal that of the `href` param. I think this would help with adoption since in many cases the href param will have all the info needed anyways.

**Comment by csharrison** [comment]
Another quick note: if we used structured headers we don't need to use a concatenated lower-casing naming scheme, we can do something a bit more ergonomic like hyphen separated lowercasing.
