### ISSUE TITLE
[Spec bug] attribution sources must be gated by transient activation

### ISSUE THREAD

**Issue by csharrison** [WICG/attribution-reporting-api#277]
See https://html.spec.whatwg.org/multipage/interaction.html#transient-activation

This is done currently in the Chromium implementation:
1. [Anchors]( https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/html_anchor_element.cc;drc=d7044ac79851029fa1698731d9ce5c251a5939be;l=520)
2. [window.open](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/local_dom_window.cc;drc=d7044ac79851029fa1698731d9ce5c251a5939be;l=2096)

**Comment by apasel422** [comment]
Should this also apply to `window.attributionReporting.registerAttributionSource`?

**Comment by csharrison** [comment]
No, `registerAttributionSource` and the other APIs that trigger `event` sources shouldn't require activation, it would jeopardize the view-through use-case.
