### ISSUE TITLE
What models may be considered in the future for the aggregation service?

### ISSUE THREAD

**Issue by palenica** [WICG/attribution-reporting-api#329]
What other models, such as outputting buckets and values if the value exceeds a noisy threshold, may be considered in future iterations?

**Comment by alois-bissuel** [comment]
Have you considered enabling the training of ML models directly in the TEE? This would create a lot of value for the API, as it is arguably a lot easier to train ML models on granular data rather than on noisy aggregated data.

**Comment by palenica** [comment]
I believe there's a good amount of interest, research and prototyping by various entities on the topic of training ML models in a TEE. That said, I'm going to close this issue for lack of activity, and hope that the conversation can continue elsewhere.
