### ISSUE TITLE
Debugging: should the "no duplicates" rule be relaxed initially?

### ISSUE THREAD

**Issue by palenica** [WICG/attribution-reporting-api#335]
There are two options worth considering: 

(a) Disable the rule, which may make it easier for adtechs to become familiar and experiment with the system. If third-party cookies are disabled by the user, we may need to prevent the client from sending aggregatable reports for privacy reasons.

(b) Enforce the "no duplicates" rule to better align with desired end state after third-party cookie deprecation.

**Comment by csharrison** [comment]
We ended up enforcing the "no duplicates" rule.
