### ISSUE TITLE
90 day attribution window

### ISSUE THREAD

**Issue by nanook21** [WICG/attribution-reporting-api#337]
For awareness campaigns that won't expect an immediate click, the proposed 30 day maximum window is too short - especially for industries that have longer sales cycles.

Can the attribution window for view-through conversions be extended longer than the click-through window to account for this? 90 days would seem appropriate to align with the current capabilities within Google Campaign Manager.

**Comment by nanook21** [comment]
Hi @csharrison, I work for an agency that does a lot of top of the funnel, brand awareness campaigns. The average response time to our client campaigns is 42 days.

The Heating and Air Conditioning industry is a good example. These businesses want to establish their brands in a market, well in advance of their peak seasons. It's rare to get an immediate click on these branding ads. What they're trying to do is establish their brands so that when your furnace breaks down a few months later, and you're looking through a list of providers, they will stand out and have you say, "oh, I've heard of those guys".

I would suggest that view-through conversions are fundamentally different than clickthroughs, and make sense to have a longer window. Supporting 90 days will make for a seamless transition for those of us who are currently reliant on GCM Floodlight tags for this use-case:
https://support.google.com/campaignmanager/answer/2823351?hl=en

**Comment by NoiseRich** [comment]
Hi @csharrison .

I work at an agency with many Travel clients. We are also a Google Marketing Platform and Analytics 360 sales partner. The consideration window for travel is often > 1 year, and we've mainly used a 90 window for view-though conversion attribution. Shortening this window will have a significant impact on measurement of travel related campaigns and could impact advertiser's spend on upper-funnel activities. We would strongly recommend keeping this 90 attribution window for view-throughs, even if this means data aggregation is required.

**Comment by nanook21** [comment]
Have there been any further developments on this?

The new GA4 defaults to a 90 day lookback window for some conversions:
https://support.google.com/analytics/answer/10597962?hl=en#window&zippy=%2Cin-this-article

This would seem to be incompatible with the Attribution Reporting API's 30 day limit.

**Comment by csharrison** [comment]
Hey @nanook21, at this point we are committed to a maximum retention period for sources of 30 days. This is an important limit for privacy that unfortuantely we aren't comfortable increasing at the moment. Additionally, we have other mechanisms we have tuned based on this limit whose privacy would degrade with this change (namely the generation of null aggregatable reports: https://wicg.github.io/attribution-reporting-api/#generate-null-reports)
