### ISSUE TITLE
Consider replacing privacy_budget_key hash with components

### ISSUE THREAD

**Issue by alexmturner** [WICG/attribution-reporting-api#365]
Instead of having the client construct a hash for the privacy_budget_key, the inputs to the hash could be provided in the shared_info field. This would allow the aggregation service to construct a hash itself, providing some additional flexibility. It would also ensure that no information is (implicitly) duplicated, preventing complicated edge cases caused by bad (malicious or broken) clients. For example, a bad client could have an inconsistency in the reporting_origin in the privacy_budget_key hash input and in its dedicated field.

We could also consider grouping these fields into a JSON sub-object (e.g. `privacy_budget_components`)

**Comment by csharrison** [comment]
I think the simplest thing to do is to just embed everything into `shared_info`:
```
{
  "attribution_destination": "https://advertiser.example",
  "report_id":"[UUID]",
  "reporting_origin":"https://reporter.example"
  "scheduled_report_time":"[timestamp in seconds]",
  "source_registration_time": "[timestamp in seconds]",
  "source_site": "https://publisher.example",
  "version":"[api version]",
}
```
