### ISSUE TITLE
Should attributionsrc requests use HEAD method instead of GET?

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#369]
Since we only care about the response headers, and not the body.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

**Comment by csharrison** [comment]
This seems fine to me in principle. Maybe it ties our hands if we wanted to get rid of the redirect support and have more rich response bodies, but that doesn't seem like a blocker.

@maudnals do you have any thoughts here from a developer experience POV?

**Comment by apasel422** [comment]
Actually, it's not clear to me how `HEAD` works with redirects.

**Comment by csharrison** [comment]
I thought HEAD requests should redirect OK but we should double check. I only looked at this [WPT](https://github.com/web-platform-tests/wpt/blob/master/fetch/api/redirect/redirect-method.any.js) which made me think it is supported.
