### ISSUE TITLE
Consider descriptive names for source types

### ISSUE THREAD

**Issue by maudnals** [WICG/attribution-reporting-api#374]
Source types can be one of `event` and `navigation`; this may be confusing, as all sources generically as _event_ sources.

Proposal:
`event` -> `view`
`navigation` -> `click`
?

**Comment by johnivdel** [comment]
In general, view/click have different meanings to different adtechs so we chose a naming more closely tied to what the sources are as perceived by the browser. A few reasons we explicitly avoided view/click:

- The API does not actually enforce any viewability requirements for ads, and using the term view may suggest the browser is doing so. "Viewed" sources are really just arbitrary event determined by the page.
- The difference between event/navigation (view/click) is that one of the events is associated with a navigation in the users browser. The fact that the ad was clicked does not substantially contribute to the rationale why navigation sources can send more reports / metadata than event sources.
- Navigation sources can be created from non-click interactions, e.g. hitting the enter button.

That being said, I agree the naming is not very intuitive. I feel most of the confusion stems from "event" being very non-descriptive versus "navigation". Open to discussion on this and the above!

**Comment by Aleksei-Gorbushin-at-Walmart** [comment]
"There are only two hard things in Computer Science: cache invalidation and naming things." (c) Phil Karlton

Quoting myself from #188 to show the clumsiness of the current naming
> * An attribution source **event** of the **event** type would be registered by a browser when a user viewed an ad.
> * An attribution source **event** of the **navigation** type would be registered by a browser when a user clicked an ad.

@johnivdel, as I can see, you want to name these events slightly more abstract. Okay, let's take a look at these events from the advertisement flow point of view. Bear with me. My expertise in ads is limited to some specific use cases only.

I'm looking at a visitor's journey through pages and sites as on downtown streets walking. There are many shops and cafes. Their windows and doors are covered with colorful posters or transparent so you can see the products they sell, their interior, and some real-life movements.

1. You could pass by paying no attention.
1. You could stop for a moment and look at a fancy-looking kettle in a tinker shop window.
1. You might be stopped by a live performance of music in a cafe and attracted by the song so deeply that you changed your walking plans and get inside.

So what can we see here? You can be affected by an advertisement but just a little so you stay **passive**. Or you can **actively** react to advertisements by doing something.

Shall we use "passive" and "active" as adjectives that characterize attribution source events?
> * A **passive** attribution source **event** would be registered by a browser when a user viewed an ad.
> * An **active** attribution source **event** would be registered by a browser when a user clicked an ad.

**Comment by apasel422** [comment]
At this point, it doesn't seem possible to rename these values, as they are integrated into the `Attribution-Reporting-Eligible` request header, the `source_type` filtering key, and the `source_type` event-level report field.
