### ISSUE TITLE
Event level reporting: Attribution source event destination url for redirects

### ISSUE THREAD

**Issue by cedelman** [WICG/attribution-reporting-api#385]
Assume an attribution source navigation event is registered via the response header below. If the destination is only a redirect to `foo.com` will the source event be logged with `foo.com`, `ad.doubleclick...` or will this source event be dropped since the final click through page doesn't match the destination `ad.doubleclick...` ?
```
Attribution-Reporting-Register-Source:
{
 "source_event_id": “123”,
 "destination": “https://ad.doubleclick.net/foo”,
}
```

**Comment by johnivdel** [comment]
Assuming this source is registered alongside a navigation to foo.com, you are correct that this will not be registered. 

The `destination` provided to the Attribution Reporting API have the same etld+1 as the page the user lands on, as noted here: https://github.com/WICG/conversion-measurement-api/blob/main/EVENT.md#handling-an-attribution-source-event
