### ISSUE TITLE
Consider replacing Attribution-Reporting-Register-Aggregatable-Source JSON list with dictionary

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#431]
Since the IDs are required to be unique anyway, this will simplify the JSON structure.

Before:
```json
[
  {"id": "campaignCounts", "key_piece": "0x159"},
  {"id": "geoValue", "key_piece": "0x5"}
]
```

After:
```json
{
  "campaignCounts": "0x159",
  "geoValue": "0x5"
}
```

https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#attribution-source-registration

**Comment by apasel422** [comment]
I'm open to using a single-field dictionary to ease future compatibility, but I'll point out that we could also go with the single string for now, and support both the single string *and* a dictionary in the future if it's ever needed. The former is certainly simpler for API implementers to deal with, though.

**Comment by johnivdel** [comment]
I think the one difference would be that a developer would be able to serve the same JSON to both new and old versions and have it work. Whereas in your example, sending the newer JSON to an older version will not work.

That being said there aren't any concrete additions to the JSON being discussed,  so the simpler string->string dictionary is probably best.
