### ISSUE TITLE
Support view registration on more HTML elements

### ISSUE THREAD

**Issue by johnivdel** [WICG/attribution-reporting-api#446]
The current explainer allows view source registration via JS, or by using the attributionsrc attribute on <img> elements. There are a variety of other HTML elements which also support making requests, such as <script>, which could presumably register sources as well.

This could make adoption easier as reporting origins won't need to transition to different request APIs, similar to the rationale given in https://github.com/WICG/conversion-measurement-api/issues/378#issuecomment-1122691996

**Comment by csharrison** [comment]
I'm not opposed to supporting any of these surfaces if it's actually useful, but we should probably not add support until there is evidence of a need of some kind, otherwise we're just adding complexity to these other elements.
