### ISSUE TITLE
Scheduled report windows

### ISSUE THREAD

**Issue by jinghao** [WICG/attribution-reporting-api#46]
Hi @csharrison and @michaelkleber !

A few weeks ago, we discussed the default attribution windows of 2 days, 7 days and (a configurable window up to 30 days). You mentioned that you only wanted the last window to be configurable, and wanted to keep the first two fixed.

I mentioned that 1-day and 7-days would be much more useful because it's much more common to have 1-day attribution windows in reporting products than 2-days. 

@csharrison mentioned that the 2-day window was arbitrary and would be open to revising it, and suggested we discuss here, so here I am! I'd love to understand whether you have any concerns with replacing the default 2-day window with a 1-day window and how to make progress on this.

Thanks!

**Comment by csharrison** [comment]
Maybe the best option here is to allow more flexibility to configure multiple windows. If the `impressionexpiry` implicitly determines the end window, it might make sense to have another field called something like `earlyreporttimes` which allows you to specify the other windows:

`earlyreporttimes="86400000,604800000"`

We would probably want to have something like day rounding to ensure that each window defines a period that is at least a day.

@johnivdel FYI for thoughts.

**Comment by akashnadan** [comment]
Moving discussion to #730 and closing this one
