### ISSUE TITLE
Storage Limits on Aggregate Report

### ISSUE THREAD

**Issue by Shakthi76** [WICG/attribution-reporting-api#462]
**Storage limits**
The browser may apply storage limits in order to prevent excessive resource usage.
Strawman: **_There should be a limit of 1024 pending aggregatable reports per destination site._**

1. What does it denotes? 
    Is 1024 denotes page size of the summary report per site.

2. Would there be separate/individual summary reports for each destination sites generated and sent to AdTech?

Could you please clarify.

**Comment by csharrison** [comment]
1. The API provides a way to receive [aggregatable reports](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#aggregatable-reports). These reports are delayed for up to 1 hour before sending over the network to a particular endpoint. The limit here means that a particular destination site (usually an advertiser) that is receiving aggregatable reports can only have 1024 separate pending reports that are scheduled to be sent at any one time in the browser.
2. Typically we expect different destination sites to receive different summary reports, but it isn't strictly necessary in the API. It should be possible for an ad-tech to combine the data from multiple different destination sites in one summary report.
