### ISSUE TITLE
Full parameterization (event-level)

### ISSUE THREAD

**Issue by martinthomson** [WICG/attribution-reporting-api#488]
There are lots of parameters in [Section 7](https://wicg.github.io/attribution-reporting-api/#vendor-specific-values) of the proposal.

I realize that Chrome is currently experimenting with the API, but the choice of parameters might be useful in informing analysis.  It would be useful to have a complete enumeration of the parameters Google decided to ship with.

(I expect to be able to find this by reading code, but I wanted to ask anyway.  If I find the time to go through and find them, I'll post them a response.)

**Comment by akashnadan** [comment]
@martinthomson we have documented the current parameters here: https://github.com/WICG/attribution-reporting-api/blob/main/params/chromium-params.md
