### ISSUE TITLE
DevX: make error messages more precise to ease debugging

### ISSUE THREAD

**Issue by maudnals** [WICG/attribution-reporting-api#498]
* When an unknown field value is used, explicitly display what are the allowed field names for that specific header (e.g. `Field must be one of...`) to make it easier to find the mistake/confusion
*  When destination contains a path/fragment, log that as well to make it easier to find the culprit
*  Tweak formatting to improve display of values within array and of nested values

(Maybe: use `console.table` to display an error table with col1 = field, col2 = error message. Same for warnings.)

**Comment by apasel422** [comment]
The new header validator provides extremely detailed error messages.
