### ISSUE TITLE
Will the ad tech not be able to collect all the events by themselve?

### ISSUE THREAD

**Issue by effectLX** [WICG/attribution-reporting-api#500]
I was wondering if the proposal assumes, that the browser will block any footprinting (etc.) in the future?
If not, wouldn't the ad tech itself be able to collect all source and trigger events themselve during registration of such. Combined with a footprint of the client, I assume that the ad tech would be able to do its own attribution.

New to the topic, pardon if I am missing anything obvious.

**Comment by csharrison** [comment]
Hey @effectLX , this design is independent from any proposals to block footprinting / fingerprinting and just unlocks the ability for an ad-tech to do this without using those tools.
