### ISSUE TITLE
DevX: Support for more trigger header misconfigurations

### ISSUE THREAD

**Issue by maudnals** [WICG/attribution-reporting-api#508]
While the validator is already super helpful as it raises errors for most misconfigurations, there are a few easy-to-make mistakes that don't raise errors or warnings yet. 

@apasel422 Could we consider adding these errors/warnings as a follow-up?, what do you think?

You can reproduce all of these by running `npm run test-trigger`; see the `data.trigger.js` file.
* Aggregatable keys are set but not values 
* Aggregatable values are set but not keys 
* A key is present in the trigger data but not in the values, or vice-versa. It's an easy mistake to make, especially if folks don't make their key names constants/variables (then this will fail silently).
* `{ event_trigger_data: [ { trigger_data: '99' } ] }` could raise an error, given that this is over the 3-bit (and 1-bit) limit. (Additionally, is there a way to check for event vs navigation separately? If not, which I guess is the case, we'd need to be a bit creative with the error message for that one.)

Maybe more to follow. I'll add ideas to this issue.

**Comment by apasel422** [comment]
@linnan-github What do you think about the first 3 list items in the issue description? Does it make sense to add warnings about these?

**Comment by apasel422** [comment]
@linnan-github Please correct me if I'm wrong, but my understanding is that the following from the issue description is overly strict:

> A key is present in the trigger data but not in the values, or vice-versa. It's an easy mistake to make, especially if folks don't make their key names constants/variables (then this will fail silently).

IIUC, if a key is in the `aggregatable_trigger_data.source_keys` field, it *must* be present in the `aggregatable_values` field to have any effect, but a key in the `aggregatable_values` field doesn't *have to* be present in the `aggregatable_trigger_data.source_keys` field to have an effect. In the latter case, it's as if the key was present with `key_piece: "0x0"`.

**Comment by linnan-github** [comment]
> @linnan-github Please correct me if I'm wrong, but my understanding is that the following from the issue description is overly strict:
> 
> > A key is present in the trigger data but not in the values, or vice-versa. It's an easy mistake to make, especially if folks don't make their key names constants/variables (then this will fail silently).
> 
> IIUC, if a key is in the `aggregatable_trigger_data.source_keys` field, it _must_ be present in the `aggregatable_values` field to have any effect, but a key in the `aggregatable_values` field doesn't _have to_ be present in the `aggregatable_trigger_data.source_keys` field to have an effect. In the latter case, it's as if the key was present with `key_piece: "0x0"`.

Yes, that is correct.
