### ISSUE TITLE
TPAC 2022

### ISSUE THREAD

**Issue by lbdvt** [WICG/attribution-reporting-api#512]
Hi,

Will there be a session during TPAC 2022 for discussions around the Attribution Reporting API?

**Comment by lbdvt** [comment]
And the same question goes also for FLEDGE, which is also currently hosted at the WICG.

(Assuming the TOPICS may be discussed as part of the PATCG meeting).

**Comment by michaelkleber** [comment]
I don't think WICG chairs have collected requests for TPAC sessions yet — @yoavweiss have I missed something?

Personally I would like to have a session on the FLEDGE-and-PARAKEET API family, and I think @erik-anderson is on board with this idea.  But I'm not sure how that turns into a scheduled event.

**Comment by yoavweiss** [comment]
We have WICG slots for Friday morning and afternoon, but haven't talked to the various incubations yet. How much time would y'all need?

**Comment by michaelkleber** [comment]
I think FLEDGE+PARAKEET would like 60 to 90 minutes.  (But note that this Issue from Lionel is about the Attribution Reporting API; the FLEDGE discussion was due to a drive-by mention.)

**Comment by lbdvt** [comment]
Thanks @michaelkleber!

We will be interested in that FLEDGE+PARAKEET session.

Going back to the Attribution Reporting API, we would be interested in a session to discuss plans around the event-level and aggregated APIs. Is one already planned?

**Comment by yoavweiss** [comment]
I added a line to the [spreadsheet](https://docs.google.com/spreadsheets/d/17hm1eNjtPJPW_0P7XdPZt1333qXK55G1ppJu9CBTrPc/edit#gid=0). Please let me know who's interested in driving this session, and its duration.

**Comment by csharrison** [comment]
Thanks @lbdvt for filing. I added a line for the Attribution Reporting API and would be happy to facilitate discussion. Let's use this issue to craft an agenda.

cc @johnivdel
