### ISSUE TITLE
Make source_event_id optional

### ISSUE THREAD

**Issue by maudnals** [WICG/attribution-reporting-api#517]
In case one is only interested in summary reports, is the `source_event_id` strictly necessary for them? Is there a reason it's particularly helpful for us to nudge developers into using it by mandating it?

If not, shall we consider making this an optional field?

cc @apasel422 @linnan-github

**Comment by apasel422** [comment]
I don't see a problem with defaulting this to `0` if omitted.

**Comment by maudnals** [comment]
Sounds good.
