### ISSUE TITLE
Enable a different trigger data for event and navigation

### ISSUE THREAD

**Issue by alois-bissuel** [WICG/attribution-reporting-api#520]
Hello,

In the current API, one has to declare a trigger data which will be sanitized to either 3 bits (if it is matched to a navigation source) or 1 bit (if it is matched to an event source). A user of the event-level attribution reporting API may have a very different expectation of what they want to track depending on the attribution method (ie post click or post-view). If my understanding is correct, for now only the trigger data = 0 means the same type of event for both navigation and event sources, and trigger data from 1 to 7 for navigation means 1 for an event source.

Would it be possible instead to have two fields in the `Attribution-Reporting-Register-Trigger` header (ie something along the lines of `event_trigger_data` and `navigation_trigger_data`) to declare both a trigger_data, a priority and a dedup key for both navigation and event sources?

**Comment by johnivdel** [comment]
I believe this functionality can already be achieved using the trigger side filtering: https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#optional-attribution-filters

The example given in the explainer:

```
// Filter by the source type to handle different bit limits.
{
  "event_trigger_data": [
    {
      "trigger_data": "2",
      // Note that "not_filters", which filters with a negation, is also supported.
      "filters": {"source_type": ["navigation"]}
    },
    {
      "trigger_data": "1",
      "filters": {"source_type": ["event"]}
    }
  ]
}
```
shows that you can provide a different data based on whether the trigger is associated with a navigation / event source. Note that the "source_type" filter is set automatically by the browser depending on what type of source is being attributed by the trigger.

Priority and dedup key can also be varied using this same approach.
