### ISSUE TITLE
consider Structured Field Value instead of JSON in HTTP header

### ISSUE THREAD

**Issue by JackJey** [WICG/attribution-reporting-api#538]
`Attribution-Reporting-Register-Source` sends JSON as value but it's better to use Structured Field Values instead, since it standardized for replace JSON in header field values.

https://www.rfc-editor.org/rfc/rfc8941.html

**Comment by apasel422** [comment]
Thanks for the suggestion. We considered this, but structured headers do not support the level of nesting needed by the API.

See https://github.com/WICG/attribution-reporting-api/issues/194#issuecomment-1132964270 for details.

**Comment by JackJey** [comment]
Hmm I see, Thanks.
