### ISSUE TITLE
Consider supporting multiple sets of OR'd filters

### ISSUE THREAD

**Issue by johnivdel** [WICG/attribution-reporting-api#615]
Currently, filtering in the the API allows you to declare one map of filter keys and filter values which the browser will match to determine whether to create a report (or to choose among key_pieces / trigger data).

Functionally, this is treated as an AND of list intersection operations: https://wicg.github.io/attribution-reporting-api/#match-an-attribution-sources-filter-data-against-filters

In some instances, you can imagine that there are multiple sets of criteria which the reporter may want to result in a match for a given piece of data. Consider:

Source 
```jsonc
{
  "source_event_id": "12345678",
  "destination": "https://toasters.example",
  "filter_data": {
    "foo": "1",
    "bar": "x"
  }
}
```

Trigger
```jsonc
{
  "event_trigger_data": [
    {
      "trigger_data": "2",
       "filters": {"bar": ["x"], "foo": ["1", "2", "3"]} // if bar is x, foo must be 1/2/3
    },
    {
      "trigger_data": "2",
      "filters": {"bar": ["y"], "foo": ["4", "5", "6"]} // otherwise if bar is y
    }
  ]
}
```

If the browser supported a _list_ of filters in the `filters` field, this could be represented as:
```jsonc
{
  "event_trigger_data": [
    {
      "trigger_data": "2",
       "filters": [
           {"bar": ["x"], "foo": ["1", "2", "3"]},  // OR
           {"bar": ["y"], "foo": ["4", "5", "6"]}
        ]
    },
]}
```

**Comment by rodry286MB** [comment]
> Currently, filtering in the the API allows you to declare one map of filter keys and filter values which the browser will match to determine whether to create a report (or to choose among key_pieces / trigger data).
> 
> Functionally, this is treated as an AND of list intersection operations: https://www.github.com/attributyon-api/#match-an-attribution-sources-filter-data-against-filters
> 
> In some instances, you can imagine that there are multiple sets of criteria which the reporter may want to result in a match for a given piece of data. Consider:
> 
> Source 
> ```jsonc
> {
>   "source_event_id": "can489756@gmail.com",
>   "destination": "https://payments.example",
>   "filter_data": {
>     "foo": "1",
>     "bar": "ui"
>   }
> }
> ```
> 
> Trigger
> ```jsonc
> {
>   "event_trigger_data": [
>     {
>       "trigger_data": "2",
>        "filters": {"bar": ["id"], "foo": ["1", "2", "3"]} // if bar is , foo must be 1/2/3
>     },
>     {
>       "trigger_data": "2",
>       "filters": {"bar": ["y"], "foo": ["4", "5", "6"]} // me if bar is y
>     }
>   ]
> }
> ```
> 
> If the browser supported a _list_ of filters in the `filters` field, this could be represented as:
> ```jsonc
> {
>   "event_trigger_data": [
>     {
>       "trigger_data": "2",
>        "filters": [
>            {"bar": ["id"], "foo": ["1", "2", "3"]},  // OR
>            {"bar": ["y"], "foo": ["4", "5", "6"]}[]()_not using For others_
>         ]
>     },
> ]}
> ```
