### ISSUE TITLE
Scheduled reporting time for Event API

### ISSUE THREAD

**Issue by chandan-giri** [WICG/attribution-reporting-api#648]
In order to indicate the correct reporting window of a particular event report, we should
include “scheduled_reporting_time” in the event reports ( much like they are included today in the aggregate reports). This is needed since the event reported data has further delay exceeding the API spec. With a scheduled_reporting_time, we can place the reports to the right reporting window, despite additional and unexpected delays.

This should be the time when the supposed reporting window for this event has reached.

Here are few examples:
If a click occurs at time t0 (in seconds), and the conversion happens to be in the first window, the scheduled_reportong_time for this event should be

> scheduled_reporting_time = t0 + 2*864000

If the conversion were to be in 2nd window, then 

> scheduled_reporting_time = t0 + 7*86400

If the conversion were to be in 3rd window, then 

> scheduled_reporting_time = t0 + min(event_expiry_in_days, 30) *86400

**Comment by apasel422** [comment]
Effectively the same as #47.

**Comment by csharrison** [comment]
Let's close this one and focus discussion on #47.
