### ISSUE TITLE
Allow filtering aggregation keys

### ISSUE THREAD

**Issue by johnivdel** [WICG/attribution-reporting-api#649]
Currently, the API only supports filtering on key_pieces, rather than keys themselves. This means that you cannot control what aggregation keys get recorded for a trigger based on cross-site data, but instead only source side data.

**Comment by linnan-github** [comment]
We may consider allowing `aggregatable_values` field to specify a lists of values with filters, and similar to `aggregatable_deduplication_keys`field, the first `values` in the list with matching filters will be used. 

```jsonc
{
  "aggregatable_values": [
    {
      "values": {
        "a1": 1092,
        "a2": 1234,
      },
      "filters": ...,
      "not_filters": ...
    },
    {
      "values": {
        "a1": 1638,
        "a2": 4321,
      },
      "filters": ...,
      "not_filters": ...
    }
  ],
  ...
}
```
