### ISSUE TITLE
Feedback: VAST Update Proposal for Chrome Privacy Sandbox Attribution Reporting API Support

### ISSUE THREAD

**Issue by jfggit** [WICG/attribution-reporting-api#653]
For background, the [Video Ad Serving Template (VAST)](https://iabtechlab.com/wp-content/uploads/2019/06/VAST_4.2_final_june26.pdf) is an interface published by the [Interactive Advertising Bureau (IAB)](https://www.iab.com/) Tech Lab to facilitate passing metadata associated with video or audio ad serving. It's an XML-based specification that allows advertisers and ad techs to provide a variety of data, including references to ad resource files and tracking URLs for video lifecycle events (e.g. play progress, clicks, impressions), to the publishers and ad SDKs who are responsible for video playback and event reporting.

I've written a [proposal to update the VAST specification](https://docs.google.com/document/d/1PNrTjCu2kNL8rCJm_crzifYnkER7n2E7v7zIuHgL6Hg/edit?usp=sharing) so that video ad SDKs can support registering VAST events for attribution tracking on behalf of advertisers and ad techs who want to record conversion sources. The idea is a relatively simple translation of the API into the VAST language, as well as some technical support details. The concept of an attribution type has been added to avoid any ambiguity between single-ping and dual-ping attribution registration types, and to potentially provide flexibility when it comes to any future updates or versions. Feedback from the Chrome and the community would be appreciated, particularly to confirm the technical details and examples provided are correct and appropriate.

**Comment by csharrison** [comment]
Thanks Jon! Would you be willing to present this work at one of our face to face meetings (every other Monday morning, next one is on Jan 9)? I think the group would be interested.

**Comment by jfggit** [comment]
Sure, sounds good.

**Comment by csharrison** [comment]
Hey @jfggit , do you think this issue can be closed given that the open gap we identified (https://github.com/WICG/attribution-reporting-api/issues/718) has been addressed?

We can of course re-open if we find more gaps.

**Comment by jfggit** [comment]
Sounds good.
