### ISSUE TITLE
Poisoning Inputs In Order to Cripple or Discard a Competitor's Reports

### ISSUE THREAD

**Issue by johnwilander** [WICG/attribution-reporting-api#69]
https://github.com/WICG/conversion-measurement-api/issues/40 describes an attack where "Cheater.pub wants to make it look like they are driving more conversions than they actually are." Most of the conversation in that issue is on how to ensure the integrity of the report with what I interpret as the intent to discard reports if they contain poisoned data.

You can also imagine an attack where EvilAdNetwork wants to cripple or destroy its competitor BenignAdNetwork's aggregate data reports. That can be done very similar to what Cheater.pub is doing in https://github.com/WICG/conversion-measurement-api/issues/40 by for instance reporting large sets of low value conversions, but could also deliberately inject bad data that will invalidate the whole report and deny BenignAdNetwork its measurement all together. A denial of service attack if you will.

(Charlie Harrison and I recently discussed this issue in the W3C Privacy CG Slack channel.)

**Comment by quasicomputational** [comment]
I had the same thought, and I likewise wondered if cryptography was the right answer here. I think it's a simpler problem than #40, though, which cares about lots of reports; this only needs single reports to be authenticated, and the advertiser is trusted here (right?).

If conversion reports had to be signed by a key owned by the advertiser, then the adtech network can just discard any where the signature is wrong. The advertiser doesn't have to see the impression identifier: the actual thing sent to the advertiser to be signed could be hash(r) || xor(impression identifier, r), where r is 64 random bits, and then r and the signature can be sent as part of the conversion report. The advertiser can refuse to sign anything until a conversion has actually happened (or possibly do it as part of the conversion flow?), so this can (should) rule out any bogus 'conversion' reports.

Not that I'm a cryptographer or anything! And this is skipping all of the hard questions of key distribution and stuff.

**Comment by csharrison** [comment]
Our current proposal in this space is here: https://github.com/WICG/attribution-reporting-api/blob/main/report_verification.md

This is the best thing we could come up with within our privacy constraints. I'm gonna close out this issue for now, but if there are follow-up let's file them as feedback to the new proposal.
