### ISSUE TITLE
Post click measurment and link decoration for non-targeted advertising

### ISSUE THREAD

**Issue by BasileLeparmentier** [WICG/attribution-reporting-api#71]
Hi Michael,
(this is a repost of issue 31 in FLOC as I understand this was not the right place to discuss it https://github.com/jkarlin/floc/issues/31 )

Do you mean that somehow the browser would clean / filter any 'link decoration'?

UTM_source, one of the most frequent 'link decoration' in use today, is a backbone of advertising measurement, championed most notably by Google Analytics ("GA"), the largest website traffic monitoring tool in the world. It is used by advertisers to compare performance and shift budget between different marketing channels, exposing a full range of signals, from clicks, to bounce rate, to sessions, to conversions, etc.

UTM_source is not so much a way to declare where the user came from, but rather how he arived on the website ('Facebook_video_ad', 'criteo_consideration', 'google_retargeting', etc...). This usage does not seem to infringe any of the Privacy Sandbox principles. Sure, nothing enforce the fact that UTM_source is used in this fashion. But it is an important usage nonetheless, if only for accountability. And rather than killing it, it would be better to make it more robust.

Losing UTM_source would mean that GA becomes obsolete for the Open Web, as many of these signals, crucial for advertisers (especially when they use contextual advertising, are gone. Do you plan on giving enough flexibility in the Conversion Measurement API to cover all current GA metrics?

GA also extends beyond Open Web display and video impressions, to encompass a full suite of Google first party assets like Youtube, Gmail, Search, Shopping, etc. The 'level playing field' that you guys mentioned a few weeks ago during our weekly calls certainly means that GA wouldn't use link decoration or anything of the sort to track performance outside of open web, giving these proprietary channels an unfair advantage in the process, correct?

Extending the argument, will these channels be subject to noise, delay, and high level aggregation as well?

**Comment by BasileLeparmentier** [comment]
Hi all,
We discussed this topic this week at the W3C meeting. 
I will post a summary of our discussion, @michaelkleber  @csharrison can you please correct / confirm or comment?
What I understood from Google chrome is that:
1. Link decoration is an issue because even in non-targeted world (meaning fully contextual or FloC based advertising) it could be used to link personal information across sites. 
2. There is no on-going project to retire them but point 1) still stands.
3. This means that the preferred endgame for Chrome is that all advertising (including non-targeted or not real-time advertising) would have to migrate to the proposed conversion measurement API, with its privacy mechanism principles, leading to a loss in measurement accuracy. This means for instance that the accuracy of google analytics is likely to be reduced because of differential privacy.

**Comment by csharrison** [comment]
Closing as it seems like this was resolved in F2F.
