### ISSUE TITLE
Filters and event-level data

### ISSUE THREAD

**Issue by alois-bissuel** [WICG/attribution-reporting-api#715]
Hello,
When using filters to selectively change the event-level trigger data, there might be the case that all declared filters match. 
For instance, on the source side, if one uses
`"filter_data": {"tightest_filter":["match"], "tight_filter":["match"], "loose_filter":["match"]}`
 and on the trigger side:
``` 
"event_trigger_data": [
    {"trigger_data": "2", "filters": {"tightest_filter":["match"], "tight_filter":["match"], 
                                      "loose_filter":["match"]} },
    {"trigger_data": "3", "filters":  {"tight_filter":["match"], "loose_filter":["match"]} },
    {"trigger_data": "4", "filters": {"loose_filter":["match"]} },
]
```

I think the following sentence from the [doc](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#optional-attribution-filters) tackles this case, but I am not sure to interpret it correctly:

> If the filters match for multiple event triggers, the first matching event trigger is used.

Do I understand correctly that here the selected trigger data will be 2 as it is the first one on the list?
Thanks a lot!

**Comment by apasel422** [comment]
> Do I understand correctly that here the selected trigger data will be 2 as it is the first one on the list? Thanks a lot!
Yes.

**Comment by alois-bissuel** [comment]
Thanks a lot!
