### ISSUE TITLE
Trigger time for fake reports

### ISSUE THREAD

**Issue by arpitjainx** [WICG/attribution-reporting-api#727]
Should the trigger time for fake reports referenced in the [draft spec](https://wicg.github.io/attribution-reporting-api/#obtain-a-fake-report) be `null` as it's immaterial to the generation of fake reports?

Chromium's current implementation appears to be using `report time - 1 hour` although it's not sent out in the reports: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/attribution_reporting/attribution_storage_delegate_impl.cc;l=234;drc=914e7555c8c489a8d74fcc21c4101a64396cbd7a.

**Comment by csharrison** [comment]
Arpit, does this make the spec text clearer to you? I think we chose this initially because it "simulates" a trigger time that would produce the correct report time, which keeps the relationship between trigger time and report time consistent. I'm not opposed to this, but I feel like it's a subjective choice which leads to more clear behavior.

**Comment by arpitjainx** [comment]
I agree it's a somewhat subjective choice and I don't feel strongly about it being set either way as the algorithm specified in the spec doesn't use `trigger time` anywhere, nor is this time currently sent in the debug reports.
But I'm not sure if I understood how it helps with simulating a trigger time that produces a consistent report time. IIUC when the trigger takes place immediately after a navigation source, for a real report the report time would be 1 hour after the first early deadline (if the event report window duration is larger than it) instead of a randomly selected deadline, as is the case with fake reports.

**Comment by csharrison** [comment]
> But I'm not sure if I understood how it helps with simulating a trigger time that produces a consistent report time. IIUC when the trigger takes place immediately after a navigation source, for a real report the report time would be 1 hour after the first early deadline (if the event report window duration is larger than it) instead of a randomly selected deadline, as is the case with fake reports.

The is that we choose a random deadline and then choose a trigger time that is consistent with that deadline. I guess my question to you is whether the spec is clearer if `trigger_time` is set to null?
