### ISSUE TITLE
[Event-level] Noise level and intermediate reporting windows

### ISSUE THREAD

**Issue by alois-bissuel** [WICG/attribution-reporting-api#734]
Hello,

The noise level is fixed for clicks (ie navigation sources) at 0.24%. 

If we follow the randomized response mechanism described in the [Differential privacy](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#differential-privacy) section, the noise level depends on the number of possible output states of the API, which itself depends on the number of intermediate reporting windows.

If we use an attribution window of less than 2 days, the number of possible state is `((8+3) choose 3) = 165`. According to the randomize response mechanism, the noise level with the selected epsilon value of 14 should be 0.01372% (which is far from the 0.24% for three intermediate windows).
For two intermediate reporting windows, the number of possible states is 969 and the noise level should read 0.08051%.

Would it be possible to change the noise level based on the attribution window length? Otherwise I think this puts users of the event-level API who choose it to report only on short attribution windows at a disadvantage.

**Comment by csharrison** [comment]
@alois-bissuel would you be willing to discuss this in the next meeting on Monday?

**Comment by alois-bissuel** [comment]
With pleasure!
