### ISSUE TITLE
Tracking pixel + redirect mechanism is ugly

### ISSUE THREAD

**Issue by quasicomputational** [WICG/attribution-reporting-api#74]
Tracking pixels have always been ugly hacks, and this feature's got further ugliness in checking for a redirection to a well-known URL and then parsing a query parameter to extract the conversion data. Further, it entangles conversion reporting with having a visual user agent that fetches images.

I don't understand this text:

> This redirect is useful, because this mechanism enables the reporting origin to make server-side decisions about when attribution reports should trigger.

Why should that be useful? Isn't the conversion reporting triggered by conversions - in which case, how can the reporting origin make any kind of decision before the conversion report itself? I note that 'attribution report' is a *hapax legomenon* in the explainer, so maybe something got lost during revision.

I also don't understand why the reporting origin is the one that's setting conversion data via the redirect-parsing method; isn't the only reasonable thing to pass through what the advertiser tells it, since only the advertiser knows what the conversion actually consisted of? In which case, doesn't it make more sense for the advertiser to provide the conversion data directly to the UA?

Since this feature already requires UA complaisance, I'm not sure why an all-around more direct route can't be pursued here. #22 is asking for a JS API, which might be part of the answer, but I wonder about a more declarative solution, especially since the tracking pixel mechanism doesn't require any JS either.

As a strawman, here's a design that I think is much clearer in intent: when a conversion occurs, the advertiser's website can include a `meta` element with `conversion-data` and `reporting-origin` attributes, e.g., `<meta name=conversion-report conversion-data=5 reporting-origin=adtech.example>`. When the UA sees such a `meta` element (which could be script-added!), it will then schedule a conversion report to the reporting origin with the conversion data.

If that strawman wouldn't suffice, the reasons why should probably go into the explainer to keep people like me from being confused and to show that the tracking pixel + redirect mechanism really is load-bearing.

**Comment by johnivdel** [comment]
> Why should that be useful? Isn't the conversion reporting triggered by conversions - in which case, how can the reporting origin make any kind of decision before the conversion report itself? I note that 'attribution report' is a hapax legomenon in the explainer, so maybe something got lost during revision.

The redirect is to ensure that logging conversions for a given |reporting_origin| is controlled by |reporting_origin|. For example, if the browser instead intercepted POSTs to a well-known url, |malicious_origin| could log fake conversions for |reporting_origin|. The redirect allows |reporting_origin| to consent to the event, and also to decide if it does want to measure the event with the API. E.g. the advertiser might log a sign-up event, but the |reporting_origin| may not treat that as a conversion. 

> I also don't understand why the reporting origin is the one that's setting conversion data via the redirect-parsing method; isn't the only reasonable thing to pass through what the advertiser tells it, since only the advertiser knows what the conversion actually consisted of? 

In this setup, the advertiser passes information about the conversion event in the initial GET request that is redirected. An example might be:

GET `https://<reporting_origin>/conversion?adv=advertiser.example&event=purchase&value=20&...`
REDIRECT `https://<reporting_origin>/.well-known/register-conversion?conversion-data=2`

This allows the reporting origin to translate the advertiser's representation of the conversion event into the reporting origins notion of the event, represented by `conversion-data`.

The <meta> tag proposal doesn't address these two key issues of:
  - another origin with JS access logging fake conversions for a different reporting origin
  - this translation of advertiser conversion event info into `conversion-data` which can be processed by the browser and the reporting origin

While the <meta> tag could work if the reporting_origin had javascript on the page, that is a better case for having a JS interface.

**Comment by csharrison** [comment]
You both raise good points. The security aspects of the redirect were what appealed to us, although we could consider an alternative scheme that preserves these.

@johnivdel , what do you think of a JS based conversion registration API that needs to be scoped to the reporting origin? An iframe provides similar protections. I am not sure how easy it would be for existing ads tags to migrate to some more isolated execution environment like an iframe (or a worklet...), but it might be workable as a parallel API.

**Comment by johnivdel** [comment]
I think that sounds reasonable. I do think that usage becomes more complicated as information now needs to be injected into the reporting origin's context.

E.g., if there is a purchase on https://advertiser.example, they will either need to create an iframe whose src or name attribute contains information about the conversion, or separately postMessage down to the iframe about the conversion event. Then the isolated execution context needs to invoke the API.

Another option that could be that we use the origin of the currently executing script as the reporting origin when the API is called. The advertiser sites frame could then invoke whatever API the reporting origin script exposes, and it could register the conversion if it meets the criteria. This makes the reporting origin implementation simpler, although I haven't though t through all the ways this changes the protections provided by the redirect. wdyt?

**Comment by csharrison** [comment]
>  I do think that usage becomes more complicated as information now needs to be injected into the reporting origin's context.

I agree, but ads code does this sort of thing regularly.

> Another option that could be that we use the origin of the currently executing script as the reporting origin when the API is called

This one makes me a little nervous. I don't know of many existing APIs that do security checks this way except for the 3P Origin Trial framework in Chrome. There may be implementation challenges for non-Chromium browsers too.
