### ISSUE TITLE
Consider a maximum # of reports per source for aggregatable sources

### ISSUE THREAD

**Issue by csharrison** [WICG/attribution-reporting-api#740]
This is related to the cross-site information leakage discussed in https://github.com/WICG/attribution-reporting-api/issues/738 and https://github.com/WICG/attribution-reporting-api/issues/439. If an adversary triggers many reports for a given source, the protections we are thinking about degrade.

One way to help this situation would be to set a limit. As a strawman, I am thinking of something like 20 aggregatable reports per source, but feedback welcome.

**Comment by alois-bissuel** [comment]
Out of curiosity, which protections are you thinking about? Is it an issue about generating fake reports?

Also, would this limit apply to the Private Aggregation API? I guess that there the limit would be reset daily.

**Comment by csharrison** [comment]
> Out of curiosity, which protections are you thinking about? Is it an issue about generating fake reports?

Yes, unless e.g. we unconditionally generate a report whenever a trigger happens (which leaks 0 x-site information), the null report proposal still leaks _some_ info in a way that can be amplified if you attempt to generate N reports. The goal here is basically to just bound N so at least the leak is bounded.

> Also, would this limit apply to the Private Aggregation API? I guess that there the limit would be reset daily.

Right now there isn't a PAA proposal to introduce null reports in this same way (the report_verification proposal actually does [propose to unconditionally generate reports](https://github.com/patcg-individual-drafts/private-aggregation-api/blob/main/report_verification.md#deterministic-number-of-reports) which gets around this issue).
