### ISSUE TITLE
Aggregated Conversion Reporting for metadata other than campaign level

### ISSUE THREAD

**Issue by moizarafat** [WICG/attribution-reporting-api#75]
Hello,

The document https://github.com/WICG/conversion-measurement-api/blob/master/AGGREGATE.md talks about campaign level aggregation as an example and the `<a>` tag attribute `aggimpressiondata=”a=xyz,b=20”`. Does this mean, aggregations could be done on metadata other than campaigns?

Thanks

**Comment by csharrison** [comment]
Yes we could in theory support all sorts of different slices of aggregate reporting, not just by campaign.

**Comment by moizarafat** [comment]
Thanks for the confirmation. Would this mean, using the approaches as specified in https://github.com/WICG/conversion-measurement-api/blob/master/SERVICE.md, we would be able to able to ask for an aggregate report on the all the distinct campaign numbers in the individual reports provided they satisfy the privacy and threshold rules? We would not know all the  campaign numbers in the individual reports prior to the request.

**Comment by csharrison** [comment]
Yes that should be possible. Note there are some technical issues with querying for keys where the domain is not known or enumerable before hand (e.g. you need to apply thresholding for privacy), but it's a use-case we want to support.

**Comment by moizarafat** [comment]
Thank You!!
