### ISSUE TITLE
Inquiry about Google Attribution Reporting API and DMA Compliance

### ISSUE THREAD

**Issue by hengtang** [WICG/attribution-reporting-api#754]
Hello,

I hope you're all doing well. I am currently working on an exploration that involves integrating with the Attribution Reporting API for our digital marketing efforts. As our team strives to comply with all relevant regulations, we are particularly concerned about ensuring that our implementation is in accordance with [the Digital Marketing Act (DMA)](https://en.wikipedia.org/wiki/Digital_Markets_Act).

I have searched through the documentation and previous issues, but I couldn't find any specific information regarding the compliance of the Google Attribution Reporting API with the DMA.

Could you please provide some clarification or point me to any resources that detail the compliance of the Google Attribution Reporting API with the Digital Marketing Act? We want to make sure our implementation is fully compliant with the relevant regulations and avoid any potential issues down the line.

Any guidance, advice, or insights would be greatly appreciated!

Thank you in advance for your help.

**Comment by csharrison** [comment]
Hi @hengtang! Unfortunately we cannot provide legal advice concerning the usage of this API. This is something you should discuss with your own lawyer.
