### ISSUE TITLE
ARA access on http sites?

### ISSUE THREAD

**Issue by jfggit** [WICG/attribution-reporting-api#766]
I think I had a possibly mistaken notion that access to the Attribution Reporting API was not allowed on non-secure/http sites, but that does not seem to be the case in local testing and I can't find any documentation to that effect. Is there any such limitation to be aware of?

**Comment by csharrison** [comment]
Our spec is a little sparse at the moment but we do have this restriction. See e.g. step 3 in https://wicg.github.io/attribution-reporting-api/#make-a-background-attributionsrc-request.

How were you testing this?

**Comment by jfggit** [comment]
I have the attribution API manually enabled by flag in my local Chrome (per demo instructions), and I just loaded up an ad tag on an http site. But ah, I see my mistake. The request and response headers are indeed set, but I see in attribution-internals that they're not actually getting registered.

Ok. So if I'm reading that spec correctly, only the containing context matters? So, for example, an https iframe inside of an http page would be ok? But firing from inside of an http context wouldn't work?

**Comment by apasel422** [comment]
Feel free to reopen if there's an actual issue here.
