### ISSUE TITLE
Use only the aggregate API for some sources

### ISSUE THREAD

**Issue by alois-bissuel** [WICG/attribution-reporting-api#768]
Hello,

We want to use only the aggregate API for some type of sources (namely events). 
What would be the best method for doing this? I initially thought that using an `event_report_window` of 0 would work, but some preliminary tests show otherwise  (and indeed the [technical documentation](https://wicg.github.io/attribution-reporting-api/#obtain-a-source-expiry) also says that windows cannot be smaller than 1 day).

Using filters should work (see [answer](https://github.com/WICG/attribution-reporting-api/issues/520#issuecomment-1189242566) by @johnivdel in issue #520), but it feels a bit cumbersome, as the onus is put on the trigger for something which is already known at source registration time. For instance, if I want to restrict on only some event sources, I could add some more fields in the `filter_data`, but I fear that this might be more error-prone.

To me, setting the `event_report_window` to 0 would be more elegant. What do you think?

**Comment by csharrison** [comment]
The use-case seems totally fine to support, I think we should spend a bit of time coming up with the best surface to express this though. `event_report_window = 0` kind of works but also seems a bit roundabout. You could similarly make an argument for sentinel values for other event-specific parameters like setting `source_event_id` to 0 or omitting it.

I agree w/ you that being able to specify this in the source is preferred over using the filters.

**Comment by apasel422** [comment]
Fixed by #856.

**Comment by alois-bissuel** [comment]
@apasel422, we tried setting `max_event_level_reports` to 0, and it looks like the source is not registered in that case.
Do you know what might be going on?
I am testing on Canary 119.0.6036.0

**Comment by apasel422** [comment]
> @apasel422, we tried setting `max_event_level_reports` to 0, and it looks like the source is not registered in that case. Do you know what might be going on? I am testing on Canary 119.0.6036.0

Are you seeing any errors in either the Attribution Reporting internals UI or DevTools?

**Comment by alois-bissuel** [comment]
So there are no sources registered in the Attribution Reporting internals UI. I can't remember seeing any particular error in the DevTools console, let me check.

**Comment by apasel422** [comment]
Does the header validate properly according to https://wicg.github.io/attribution-reporting-api/validate-headers? If possible, it would help to provide the whole source registration here.

**Comment by alois-bissuel** [comment]
I was just checking it at the same time, and it looks like we indeed have an error. Sorry for the noise...
