### ISSUE TITLE
Reject registrations with invalid input instead of setting silent defaults

### ISSUE THREAD

**Issue by giladbarkan-github** [WICG/attribution-reporting-api#793]
Our primary concern is that silent defaults make it impossible in some cases for ARA consumers to know about an issue. 

Let's say an ad-tech is using an expiry: 86400 instead of expiry: "86400". ARA would extend it to 30 days without notifying them and change their attribution logic.

In case of rejection, 
- They won't receive source success reports
- They'll also not receive event/aggregate report which will force them to look into the issue during integration.

Specific places we noticed:

#### Source registration
source_event_id
expiry
event_report_window
aggregatable_report_window
priority

We would argue not to reject a registration if debug_key is invalid.

#### Trigger registration
event_trigger_data -> trigger_data
event_trigger_data -> priority
Aggregatable_deduplication_keys -> dedupKey -> deduplication_key

**Comment by csharrison** [comment]
This seems reasonable to me. @giladbarkan-github would you be interested in discussing this in our call on Monday? It's at 8am PT.

**Comment by giladbarkan-github** [comment]
Discussing this in the call on Monday at 8am PT sounds good to me! Please let me know the details.

**Comment by csharrison** [comment]
I am supportive of this, especially given that we have the success reports right now which will indicate failures to the ad-tech. Something like #801 could be follow-up work to consider when success reports go away.

**Comment by apasel422** [comment]
> We would argue not to reject a registration if debug_key is invalid.

I'm fine with this, but what is the reasoning?

**Comment by apasel422** [comment]
> expiry
> event_report_window
> aggregatable_report_window

Could you elaborate on what is considered an error here? Certainly it is an error for the field to have a type other than string or for the string to fail parsing as a base-10 signed integer, but if the value is out of range, should it be considered an error or clamped to the allowed range?

**Comment by apasel422** [comment]
What about the `debug_reporting` fields? Should a registration be rejected if the field is present but isn't a boolean?

**Comment by johnivdel** [comment]
The argument for not rejecting based on debug_key seems to be that debug_key being ignored does not change the reporting origins expectation for how attribution is done by the browser. I think `debug_reporting` should be treated similarly to debug_key for that reason.

That being said, this seems to be a fairly weak protection for developers, and it would be nice if we didn't need to special case any fields in the registration.

**Comment by apasel422** [comment]
> does not change the reporting origins expectation for how attribution is done by the browser

Wouldn't this also apply to clamping source expiry and reporting windows?

**Comment by giladbarkan-github** [comment]
With expiry and reporting windows, could we make an argument that "clamping" makes an assumption about the API consumer intentions?
