### ISSUE TITLE
Consider using structured field dictionary rather than JSON for response headers

### ISSUE THREAD

**Issue by yoavweiss** [WICG/attribution-reporting-api#802]
The explainer indicates that "The response to these requests will configure the API via a new JSON HTTP header Attribution-Reporting-Register-Source". A [structured field dictionary](https://www.rfc-editor.org/rfc/rfc8941.html#name-dictionaries) is the HTTP idiomatic way of doing that.

**Comment by csharrison** [comment]
Hey Yoav, we considered structured headers extensively in #194 but we had to move away from them because they did not support the level of nesting the API requires. See also #538 . Perhaps we should document this in a note though.

**Comment by apasel422** [comment]
See `source.schema.json` and `trigger.schema.json` in #804 for details on the registration complexity, which will only be exacerbated by the [Flexible event-level configurations proposal](https://github.com/WICG/attribution-reporting-api/blob/main/flexible_event_config.md).
