### ISSUE TITLE
Source deactivation should occur before filter checking in triggering event-level attribution flow

### ISSUE THREAD

**Issue by ThomasQuesadilla** [WICG/attribution-reporting-api#842]
Currently, sources are deactivated after filter matching, rate limit/noise checks, and report generation takes place. However, since a noised source might not lead into a report,  adtechs can have the ability to determine if the source was noised, breaking privacy guarantees. An example of this is when, given S to be a source, T to be a trigger, and E as an event report:

S2 -> S1 (noised) -> T1 -> S1 expires -> T2
- S1 can win and generate a report
- S1 + T1 -> No report generated and S2 is not deactivated because S1 is noised
- S1 expires
- S2 + T2 -> E1

S2 → S1 → T1 → S1 expires → T2 
- S1 can win and generate a report
- S1 + T1 -> E1 generated and S2 deactivated
- S1 expires
- T2 -> No report generated.

Source deactivation should not be dependent on whether the winning source was noised nor if a certain rate limit is reached. It also should not be affected by report generation. To remedy this, source deactivation should occur immediately after the trigger is matched to a source. With this, the behavior of the example above would be as follows:

S2 -> S1 (noised) -> T1 -> S1 expires -> T2
- S1 can win and generate a report
- S1 + T1 -> No report generated and S2 is deactivated
- S1 expires
- T2 -> No report generated.

S2 → S1 → T1 → S1 expires → T2 
- S1 can win and generate a report
- S1 + T1 -> E1 generated and S2 deactivated
- S1 expires
- T2 -> No report generated.

**Comment by johnivdel** [comment]
The compat risk for this change is low.

Moving the deactivation step earlier into the algorithm may result in adtechs getting different reports in some circumstances (or not report where they previously would have gotten one), but only in cases where a user had multiple interactions across different ads when rate limits in the API are hit, which should be rare.

Given the output only affects the delayed reporting, this wouldn't require any changes from developers.
