### ISSUE TITLE
[Report Verification] Number of tokens per trigger

### ISSUE THREAD

**Issue by agarant** [WICG/attribution-reporting-api#875]
**Summary** 
- Suggestion to generate 3 verification tokens per trigger. 
- ~.04% (1 in 2500) of reports that should have a token would not.
-  Is this acceptable ?

**Explanation** 
Given [null report generation](https://wicg.github.io/attribution-reporting-api/#generating-randomized-null-reports), multiple reports can be created from a single trigger. To not leak which reports are null reports while using report verification,  multiple verification tokens per trigger are generated are randomly assigned. ([spec](https://github.com/WICG/attribution-reporting-api/pull/795))

_The number of tokens generated per trigger needs to be defined._

The higher this number, the more work (for the user agent & reporting origin) and bandwidth is needed to generate report verification tokens. The lower the number, the more likely it is that a report that should have a verification token is sent without one.

This is only relevant for triggers with `source_verification_time` included. In those cases, there is a flip probability per time of .008. For the purposes of this analysis, we should consider only cases where there is a true report, as we want to avoid the true report losing out to a null report.

In this case, the number of generated reports follows a binomial distribution `B(29, .008)` since one source event time has a true report. We will generate more than 2 reports with probability .16% or around 1 in 1000.

However, this is an upper bound on coverage loss because we could still randomly assign a token to the true report. For n reports and t <= n tokens and we will correctly assign to the non-null report with probability t/n = t(n-1)! / n!

Thus P[failure] = Sum[(1 - (t/(k + 1))) * (29 choose k) * .008^k * (1 - .008)^(29-k), {k, t, 29}]

For t = 3, this yields a failure % of ~.04% which makes sense because the dominating term is (1 - 3 / 4) = .25.

Here is a table of some values:
https://www.wolframalpha.com/input?i=Table%5BSum%5B%281+-+%28t%2F%28k+%2B+1%29%29%29%2829+choose+k%29+*+.008%5Ek+*+%281+-+.008%29%5E%2829-k%29%2C+%7Bk%2C+t%2C+29%7D%5D%2C+%7Bt%2C+3%2C+6%7D%5D

[Source of analysis](https://bugs.chromium.org/p/chromium/issues/detail?id=1440744#c1)

**Comment by csharrison** [comment]
cc @baz1 @spacegnome for thoughts. Note that this analysis currently only applies if `source_registration_time` is set on triggers. If it is not, the maximum # of reports you can receive is 1 per trigger.

**Comment by agarant** [comment]
https://github.com/WICG/attribution-reporting-api/pull/1366
