### ISSUE TITLE
Consider flattening event_report_windows.end_times field

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#887]
With #885, the `event_report_windows` dictionary contains only a single field: `end_times`. We could consider flattening this for simplicity.

**Comment by csharrison** [comment]
My only concern with this is that _if_ we wanted to re-add `start_time`, it would be a backwards incompatible change to migrate to a dict unless we supported both dict-based windows and list-based windows with a default 0 `start_time`.

cc @yanzhangnyc @vikassahu29
