### ISSUE TITLE
How do you deal with deduplication?

### ISSUE THREAD

**Issue by iab-france** [WICG/attribution-reporting-api#92]
Hi,

I am writing on behalf of the dedicated IAB France taskforce working on sandbox. On the conversion measurement API, we are having an issue when it is set up more than one report recipients. 

Main use of attribution is to be able to manage deduplication, so if you use a single touch attribution models as last clic and you have more than  media touch point to the conversion, just one media platform receive the credit for the conversion, how do you manage that here?

**Comment by johnivdel** [comment]
Could you clarify what you mean by media platform? Referring to this [glossary](https://github.com/WICG/conversion-measurement-api#glossary), would this be different publishers? Or would these platforms be different reporting origins?

If these are different publishers:
Multiple events leading to a single conversion are handled by the `attribution-credit` reporting parameter. If two ads were clicked, and a conversion was registered, the last clicked ads impression data would have a report with attribution credit 100. The other report would have a credit of 0.

Credit assignment is specified [here](https://github.com/WICG/conversion-measurement-api#register-a-conversion-algorithm) and credits are defined [here](https://github.com/WICG/conversion-measurement-api#multiple-impressions-for-the-same-conversion-multi-touch).

If these are different reporting origins:
The credit assignment is done in the domain of <reporting origin, conversiondestination>. So if two ads with different reporting origins and the same destination are clicked, and a conversion is registered for each of the reporting origins, both reports will have a credit of 100.

**Comment by iab-france** [comment]
It would be advertiser i guess.

Can you illustrate please you last paragraph, let's say you have advertiser A that is running campaign on Google and Facebook. Let's say Google was the first media touch point, Facebook the second one, then the conversion. The attribution mode used is last clic and I want just Facebook to receive 100% of the credit for the conversion, is that possible?

**Comment by apasel422** [comment]
Deduplication keys are supported for both event-level and aggregatable attribution. Feel free to reopen if there are further questions here.
