### ISSUE TITLE
How do you give control to the advertiser on recipient reports?

### ISSUE THREAD

**Issue by iab-france** [WICG/attribution-reporting-api#93]
Hi,

I am writing on behalf of the dedicated IAB France taskforce working on sandbox. On the conversion measurement API, we are having an issue when you want to choose recipients for reports.

We understand here that you define who will receive the reports in the pixel on the publisher and you mention that publisher should be the one to decide who will receive the report but the use case is about advertisers, it is the advertiser that need to decide you who will receive the report? How do you deal with that?

**Comment by csharrison** [comment]
In the current API the advertiser configures this on their side at conversion registration. The reporting origin has to match on the impression and conversion side for attribution to take place:
https://github.com/WICG/conversion-measurement-api/#conversion-registration

The publisher doesn't necessarily have control over the reporting endpoint, it is just code that runs on the publisher page (could be in an iframe, etc) that sets this.

**Comment by maudnals** [comment]
@iab-france Does this answer your question? 
If not, feel free to ask a follow-up question here.
If yes, feel free to close this issue.

**Comment by maudnals** [comment]
Following up on this: [this discussion](https://github.com/WICG/conversion-measurement-api/issues/96) may relate to your question. Feel free to join that discussion!

**Comment by csharrison** [comment]
Closing for now, please open a new issue if you have more questions or concerns.
