### ISSUE TITLE
Consider variable conversion metadata buckets

### ISSUE THREAD

**Issue by csharrison** [WICG/attribution-reporting-api#99]
The current explainer for the event-level API discusses 3 bits of conversion data, with 5% noise applied — that is, with 5% chance, we send a random 3 bits, and the other 95% of the time we send the real conversion data. This is pretty inflexible.

Instead, we could consider a smooth trade-off between the number of unique ids on the conversion data(3 bits has 8 ids) and the amount of noise(here uniform 5%). Ad-tech can have the flexibility to choose the maximum number of ids and browsers would add noise accordingly to maintain similar levels of privacy.

**Comment by shigeki** [comment]
It would be great for us to have this even if the noise ratio is increased since the current 3 bits are too small for us to use for the ad measurements.
We need at least 6 bits for the conversion data.

**Comment by csharrison** [comment]
We are proposing a "flexible event" API that solves this issue:
https://github.com/WICG/attribution-reporting-api/blob/main/flexible_event_config.md

Closing for now.
