### ISSUE TITLE
WebView Attribution Reporting API not sending support header

### ISSUE THREAD

**Issue by taddcrockett** [WICG/attribution-reporting-api#995]
Hello,

I am trying to test out the app-web use case for the Attribution Reporting API and am unable to enable the WebView in my demo app to support it. 

My understanding is that when I register a source to the reporting origin from some HTML shown by the WebView, there should be a header attached `Attribution-Reporting-Support: os, web`, as detailed [here](https://github.com/WICG/attribution-reporting-api/blob/main/app_to_web.md#api-changes). However there is no such header.

Am I misunderstanding the implementation here or is this not supported on my device.

- Testing on emulator
  - Build number: URD9.230712.002.A1
  - WebView version: Android System WebView Dev 118.0.5977.3
- I have added added the [Cross App and Web Origin Trial token](https://developer.chrome.com/origintrials/#/view_trial/151996487423754241) to the HTML via `meta` tag in `head`.
- My app hosting the WebView has [declared AdServices permissions](https://developer.android.com/design-for-safety/privacy-sandbox/setup-api-access?version=beta

Thanks in advance

**Comment by apasel422** [comment]
Thanks for the report. Given that this is an implementation issue, please consider re-filing at https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/new/choose by selecting the "Attribution Reporting API" question.
